### ISSUE TITLE
OpenShot Video Projects - Reopening from Google Drive, Multiple Sessions?

### ISSUE THREAD

**Issue by JesseSaul** [OpenShot/openshot-qt#2374]
**My Question:**

I teach a section of video production at a public school where kids have personal log-ins to use PCs running Windows 10 with 2.66Ghz processors and only 4gb ram. Students are not permitted to store files locally and must use Google Drive for saving between sessions. They do usually work on the same computers though. 

When returning to the lab, students download their .osp file and go to OpenShot to open the project. Numerous pop-ups show about being unable to locate various images, clips, etc. Even downloading all images and clips to the same "downloads" folder as the .osp project file does not seem to eliminate the hang-up. 

What is proper protocol for saving a project in order to be able to upload to Google Drive and resume at a later date? Students in 6th, 7th, and 8th grade need a clear guide. I have been unable to figure out the best plan. 

Also, performance is choppy in project files prior to exporting. Is this just a result of the slow processors and limited ram here? 

Thank you!

**System Details**
 - Operating System / Distro: [Windows 10]
 - OpenShot Version [2.4.3]

**Comment by speedytechdev** [comment]
Hi @JesseSaul I believe that the issue with files has been fixed in the daily builds.(@ferdnyc )
If the performance is choppy in the previewer while editing then this is a known bug but if it is prior to exporting could you make a new issue for that. Hopefully, that helps if not let me know.

**Comment by peanutbutterandcrackers** [comment]
@JesseSaul: First and foremost - yes, like it has been said earlier, a fix just recently got in and this issue has been solved. Another fix is also waiting to get it which will solve the issue with thumbnails not being shown when opening projects in the manner that you are saying. Also, the thing is OpenShot seems to work better on GNU/Linux machines. I myself created the following video using OpenShot on my Linux Mint machine that only has 2 GB RAM.
![meet tux](https://user-images.githubusercontent.com/26764547/48016787-a1a13800-e154-11e8-9f1d-bfe2a64a6ad4.gif)

Secondly, there are still a bit of problems with OpenShot that prohibit it from being used in a production environment. However, your case seems to be a teaching environment, in which case OpenShot is excellent - as the students can learn easily about keyframes and compositing, masking and other advanced Video Editing Techniques. [Here is a guide to help you out.](https://gist.github.com/peanutbutterandcrackers/f0f666243133e0ed25abbc12a4ba23d7)

And here is how you get a hold of the [daily builds](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914).

Also, on a different note: I'd suggest you use [Linux Mint](https://www.linuxmint.com/) to teach your students. [Here](https://www.youtube.com/watch?v=Ag1AKIl_2GM) is why that might be a good thing, apart from the fact that Linux Mint is a lot more easier than normal Windows, and a lot more useful and stable. But I might be biased.

**Comment by ferdnyc** [comment]
> Hi @JesseSaul I believe that the issue with files has been fixed in the daily builds.(@ferdnyc )
> If the performance is choppy in the previewer while editing then this is a known bug but if it is prior to exporting could you make a new issue for that. Hopefully, that helps if not let me know.

My history-saving fix (PR #2400) isn't in the daily builds, since it's not merged yet. So, right now that's not available except by running it from source, with my branch checked out. Hopefully soon it'll make it into the daily builds, that's mostly up to @jonoomph .

**Comment by DylanC** [comment]
@JesseSaul - Try v2.4.4 and see how that version goes. #2400 has been merged and released.

**Comment by ferdnyc** [comment]
Just for clarity, #2400 was _briefly_ merged as a stopgap, but the code was later modified so that history is still persisted between sessions — hopefully without the bug that was causing project files to balloon out of control. That issue should be fixed which means the history shouldn't cause such a strain on the application, but loading a project file will restore the undo history from before it was saved. The 2.4.4 release doesn't include the code (#2400) to "clean slate" the project history on load.
