### ISSUE TITLE
Openshot jerky play back from time line.

### ISSUE THREAD

**Issue by firew4lker** [OpenShot/openshot-qt#24]
When paying the preview from the time line the play back is really jerky and slow. Even worst when entering a transition phase etc.

https://www.youtube.com/watch?v=Vey-aTADJFE

Previewing a file (right click -> Preview File) is just fine  though.

http://i.imgur.com/zDVXJgW.png

My system is a Core i3 with 4 G of RAM. No problem with other video editors, including Openshot 1.4.

Can I do something to provide more feedback for the issue?  

Using Arch Linux.

**Comment by jarlarntzen** [comment]
Playback slow on Ubuntu 14.04 here. Got 16 GB RAM, 4 Core CPU. Nvidia GTX 750 Ti 

Playback is reasonable on my work MacBook Pro 16 GB, El Capitan.

**Comment by nwgat** [comment]
did you try setting the current profile to match the video?
i think currently the player is not optimized for playback when scaling up or down, but when you use  same resolution/fps as source it plays back more smoothly

**Comment by jarlarntzen** [comment]
I've mostly tested OpenShot with stills (PNGs) so far. Although it did actually fare slightly better with video playback. I'll try to match the profile to the imported files or video and see what happens. Thanks for the tip @nwgat

**Comment by Bugsbane** [comment]
> i think currently the player is not optimized for playback when scaling up or down

Which leads to the discussion of proxy-editing, but that should probably be for another ticket...

**Comment by jasauders** [comment]
I'm seeing the same behavior on my end as well. Unfortunately I didn't have the better success firew4lker mentioned when using playback with right click >> preview, as mine was only marginally better and still far from what I'd expect. It was still choppy with both audio and video.

Adding transitions caused my processor to spike quite a bit, but even still slow down really started to churn as it went from clip to clip.

My profile was set to match my video clips (1080, 30fps). I double checked Nautilus file properties of the video file to verify.

Laptop is an i5, 6GB of RAM system with Ubuntu 15.10.

**Comment by nwgat** [comment]
the current binary on windows is 32-bit, and there seem to be limited multicore support, on my 8-core FX-8350 it only goes to 40% until it crashes

**Comment by asilnevs** [comment]
I also have the same problem when I preview a clip or view it from the timeline.
I did not have this problem in Openshot 1.4
My laptop specs: Intel(R) Core(TM)2 Duo CPU T9600  @ 2.80GHz / System memory: 4GB / 64 bits / NVIDIA GeForce 9600M GT / Intel  82801I (ICH9 Family) HD Audio Controller / Harddisks: 500GB SSD + 500GB HD / OS: Ubuntu 14.04 LTS
I tried this with MTS and MOV files , the media info is attached.
Hope this helps.
[MediaInfo.txt](https://github.com/OpenShot/openshot-qt/files/95751/MediaInfo.txt)

**Comment by jarlarntzen** [comment]
**Ubuntu 14.04 LTS**: Tried with a couple of .MKV clips. 
Previewing and timeline playback works well with the latter being slightly smoother and they are also equally smooth when playing back at a small scale.
At actual size or scaled larger, the playback from the timeline is still nice but the preview playback is not scaled according to aspect ratio and the UI becomes sluggish or even non-responding until preview playback is stopped.

**Comment by jonoomph** [comment]
This has been much improved in recent versions. 1080p videos plays smoothly on the timeline for me on multiple computers... and some 4k videos play reasonably well on the timeline. I'm going to close this for the moment... since the initial crappy performance has been fixed. =)

**Comment by firew4lker** [comment]
The playback is just fine now. It is only jerky while transitioning between clips.

**Comment by asilnevs** [comment]
I just want to say that I still can't play clips smoothly.
I tried other editors (Kdenlive, Flowblade, Shotcut and Lightworks) and within those programs the same HD clips play very smooth without a problem.
The processor usage of all program stays below 90%, also Openshot and the memory usage is only 1 Gig off the 4 Gig's. So the processor and memory is not an issue I think.
If I take a proxy clip with a resolution of 960x540 the preview plays normal (processor 40%) but from the timeline it stutters again (processor 80%).
In this way it's not possible for me to test Openshot further.
If you need more info, just let me know.
Thanks.

**Comment by ovari** [comment]
Having the same problem as asilnevs on Windows 8.1 64-bit.

**Comment by simonambridge** [comment]
seeing the same on a Mac Pro

**Comment by stolk** [comment]
OpenShot 2.1.0 is super jerky for me.

The old OpenShot 1.4.3 played back fluently all the time (but crashed at least once a minute.)

**Comment by Martinsos** [comment]
Jerky for me also - Archlinux 4.7.5-1.
I am mixing pngs with mp4 videos on one track, and I added mp3 sound on another track.
All was fine while there was no audio, however when I added audio preview become so jerky that it is not usable any more - makes it really hard to align the sound with the video.
Version of openshot: 2.1.0

**Comment by andydread** [comment]
Running 2.1.0 on Ubuntu 15:10.  Preview is absolutely unusable.  very jerky on a very powerful system then it eventually locks up. I'm editing 1080p/60fps 1.1GB files. old version 1.4.3 preview was fine.

**Comment by BHSPitMonkey** [comment]
Same issue on Windows 10 on 2.1.0, working on a 1080p/60fps project with a ~150MB clip. System has a 2016 i5, 16GB RAM, nVidia GTX 1070.

**Comment by jelinj8** [comment]
The same on 2016 i7, Win10 x64 32G RAM, SSD disks :-(
Not even clip preview (1920x1080x30fps, MOV from Mobius cam) is usable.

**Comment by NeuroSerpens** [comment]
This issue clearly hasn't been fixed.
I'm on Arch linux too (3rd gen i7 with 8gb ram) and the video preview is extremely jerky.

**Comment by tomcarlson** [comment]
This issue definitely not fixed.  OpenShot 2.1.0 with 16GB of RAM i7-4800MQ 2.7GHz
Very jerky playing from timeline.

**Comment by theelectricsoul** [comment]
Have to agree. Just setup a WIN 7 64 Home for a friend. Pretty jerky playback. Even 720p 25fps is as jerky as 1080p 50fps

**Comment by robertjm** [comment]
Same issue on Mac Mini running OSX 10.12.1 Sierra w/16gb memory. :-(

Then I started the project from scratch, and it crashed on me twice after adding the .mov file.

Kind of a bummer because I was trying to go away from iMovie. However, I'm having ZERO lagginess in iMovie.

**Comment by fjrg76mx** [comment]
One year and the bug is still there on the 2.2.0 release, without any plan to leave us alone! Preview worked flowlessly on 1.4 release, but 2.2.0 is a jerky as many of you have pointed it out. I have no plans to edit 4K videos, so I'll try to reinstall 1.4 'cause it's better to get some crashes from time to time than not have the chance to edit at all. Hope it's fixed soon!

**Comment by Bugsbane** [comment]
Just something to note @fjrg76mx ... Ogv videos from RecordMyDesktop are known to be notoriously buggy and not follow the ogv spec properly, causing crashes in video editors that would otherwise work fine. Have you tried editing ogv's recorded with any other app?

**Comment by fjrg76mx** [comment]
@Bugsbane This is the thing: OpenShot 1.4 (the one that is included in Linux Mint 18.1) works flawlessly with the videos I've been doing with RecordMyDesktop. The crashes I faced were because I had many apps opened, but if I only use OpenShot 1.4 everything goes ok.

The problem with OpenShot 2.2 is that it doesn't play videos fluid, as many others have said. I think 1.4 is using some kind of "low quality" preview, which makes the videos to be seen without any problems; while 2.2 is kind of using "full resolution" preview, which is too much for my elder processor. In both cases there are no options to change this behaviour.

Pitivi works ok with ogg videos, although I didn't get it, so I got stuck with OpenShot 1.4, 'cause it's what I need.

**Comment by Bugsbane** [comment]
Yeah, I get it. Things used to work and now they don't. I was just letting you know one thing that *might* be causing them to work less so you could try and work around it. Ultimately I agree with you that we want smooth playback in 2.2. :)

**Comment by Newbrict** [comment]
I have same issue :<

**Comment by fjrg76mx** [comment]
@Newbrict Try to get and install the 1.4.3 release. Apparently there are no plans to fix the bug, so as long as you don't need to edit 4K videos, the 1.4 release is ok. I tried KDEnlive but it's worst than OpenShot LOL.

**Comment by Newbrict** [comment]
@fjrg76mx I just used shotcut, thanks though, too laggy on 1080p

**Comment by Bloodwork** [comment]
Openshot is unusable for longer videos due to this issue and it's not even hgigh res on bitrate. I just doesn't like my hour long video.

**Comment by siistibuddy** [comment]
WHAT??? Why are they giving up on this?!?!?!?! This software is amazing. Timeline playback is the only issue i have. MP4 1080p Video, WAV audio and PNGs sprinkled throughout. i drop the   PLEASE PLEASE PLEASE fix this!! its not like we are being ungrateful. why close the issue without a fix :(
[Win7x64, i7-6820, 16GBram, NVME storage]

**Comment by alextpedro** [comment]
I, too, have this problem. Previewing a file is fine, but the timeline plays back with choppy audio and video. Running Linux Mint 18.1 and OpenShot 2.2.0.

**Comment by fjrg76mx** [comment]
@alextpedro Try 1.4 release, it's included in LM18.1, as long as you don't have the need to edit 4K.

**Comment by alextpedro** [comment]
@fjrg76mx Thanks, that one works. Too bad it's also a good bit clunky. Hopefully this issue will be resolved for newer versions of OpenShot.

**Comment by ronnyegner** [comment]
Hi have the same issue. I am trying to cut a 2 GB MPGV Video (PAL resolution - 720x576) on a 8-core i7 with 32 GB memory running Windows 7 64-bit with a 5 GB cache. The source video is on a SSD. Preview is completely unusable. Skipping into the video takes between 15 and 30 seconds. The longer the video, the longer it takes.

**Comment by hicnar** [comment]
Enough is enough so switched to Shotcut and very happy with it! :)

**Comment by blueto01h** [comment]
same issue here. thanks for the tip hicnar, will check it out.

**Comment by nazmifr** [comment]
That's so sad, I liked the options of openshot...

**Comment by N3WWN** [comment]
You may want to check out my comments [here](https://github.com/OpenShot/openshot-qt/issues/960#issuecomment-337678019) and [here](https://github.com/OpenShot/openshot-qt/issues/960#issuecomment-344359408) to see if they help you.

The first one talks about using disk cache and reduced quality and scale settings to improve preview latency in Openshot 2.4.0 and the second one talks about the improvement I saw with Openshot 2.4.1 over 2.4.0 which allowed me to increase the quality and scale.

**Comment by remuslt** [comment]
Hi all,

they are locking these threads for reasons.... 

Here is simple solution:  set Project frame rate to 30 fps and resolution to the one that have most of your clips.

Export in 30 fps and desired resolution.

Do not even dream using other fps, its a free soft - like or hate it. 

Enjoy.

**Comment by ferdnyc** [comment]
@remuslt Until you commented, this thread had been dormant for over two **years** so I'm not sure who you're even talking to really (never mind that it's hard to see how advice about exporting is a solution to preview performance issues...) buuuuuut,

1. We very rarely lock issues. Out of the 3192 total issues in our tracker only... [19 are locked](https://github.com/OpenShot/openshot-qt/search?o=desc&q=archived%3Afalse+is%3Alocked&s=created&type=Issues), and frankly I'm surprised the number is even that high.
1. The reason for locking a thread isn't always the same, but it's rarely a secret. Most of the time, whoever locks the issue gives a reason that's listed in the lock message at the bottom.
1. Most of the locked issues had been closed for months or **years** before they were locked — and one reason we sometimes lock old conversations is if people keep dredging them up again.
1. This is issue number **_Twenty-Four_**.
1. _Out of 3192!_
1. It was opened back when Barack Obama was still President of the US
1. Until today it had not been updated since before the Eagles won the SuperBowl.
1. ..Am I getting through at all?

The simple fact is, the problems being discussed **here** are no longer relevant. I'm not saying the current version _doesn't_ have problems — it absolutely does! Maybe some of them are even the same _kind_ of problems as the ones discussed here. But that doesn't make them the **same problems**.

It makes far more sense to discuss _current_ issues with 2.5.0 in their own thread, than to continue a very old conversation about issues with OpenShot 2.0 / 2.1 — which is what this is.

Which is why I'll do you a solid, and transfer your comment to a new issue... before I lock _this_ thread (big number 20, woo!), to prevent any **further** resurrections.

Fair warning: Since you're talking about performance issues, I'm also going to ask you to post your system details (in the new issue), and probably some settings as well. Because it's impossible to discuss performance without at least touching on hardware, and not everyone's is the same. What works for you doesn't necessarily work the same for other people. Hopefully, you'll provide the necessary info so we can try to address the problem.
