### ISSUE TITLE
Rendering failure: Error while writing raw video frame

### ISSUE THREAD

**Issue by daveho** [OpenShot/openshot-qt#2545]
Video rendering fails with an error "Sorry, there was an error exporting your video: Error while writing raw video frame".

 - Operating System / Distro: Linux Mint 18.3 (MATE Edition)
 - OpenShot Version 2.4.3

This happens every time I try to render, and is always at the same point in the progress (74.6%).

Obviously, the expected (or at least desired) behavior is to have the video render successfully :-)

I will attach a screenshot.

I enabled Debug Mode (Verbose), and there is some potentially relevant output in libopenshot.log:

    FFmpegWriter::process_video_packet (frame->number=56374.0000, bytes_source=8294400.0000, bytes_final=3110400.0000)
    FFmpegWriter::process_video_packet (frame->number=56375.0000, bytes_source=8294400.0000, bytes_final=3110400.0000)
    FFmpegWriter::process_video_packet (frame->number=56376.0000, bytes_source=8294400.0000, bytes_final=3110400.0000)
    FFmpegWriter::write_video_packet (frame->number=56369.0000, oc->oformat->flags & AVFMT_RAWPICTURE=0.0000)
    FFmpegWriter::write_video_packet (frame->number=56370.0000, oc->oformat->flags & AVFMT_RAWPICTURE=0.0000)
    FFmpegWriter::write_video_packet (frame->number=56371.0000, oc->oformat->flags & AVFMT_RAWPICTURE=0.0000)
    FFmpegWriter::write_video_packet ERROR [File too large] (error_code=-27.0000)
    FFmpegWriter::write_video_packet (frame->number=56372.0000, oc->oformat->flags & AVFMT_RAWPICTURE=0.0000)
    FFmpegWriter::write_video_packet ERROR [File too large] (error_code=-27.0000)
    FFmpegWriter::write_video_packet (frame->number=56373.0000, oc->oformat->flags & AVFMT_RAWPICTURE=0.0000)
    FFmpegWriter::write_video_packet ERROR [File too large] (error_code=-27.0000)
    FFmpegWriter::write_video_packet (frame->number=56374.0000, oc->oformat->flags & AVFMT_RAWPICTURE=0.0000)
    FFmpegWriter::write_video_packet ERROR [File too large] (error_code=-27.0000)
    FFmpegWriter::write_video_packet (frame->number=56375.0000, oc->oformat->flags & AVFMT_RAWPICTURE=0.0000)
    FFmpegWriter::write_video_packet ERROR [File too large] (error_code=-27.0000)
    FFmpegWriter::write_video_packet (frame->number=56376.0000, oc->oformat->flags & AVFMT_RAWPICTURE=0.0000)
    FFmpegWriter::write_video_packet ERROR [File too large] (error_code=-27.0000)

**Comment by daveho** [comment]
![screenshot at 2019-01-20 12-41-05](https://user-images.githubusercontent.com/691146/51443150-6f629980-1cb2-11e9-8775-ab66b32de227.png)

**Comment by peanutbutterandcrackers** [comment]
A possible reason might be that exporting raw video frame is using up all the hard drive space. Could you please make sure if that is (or is not) the case?

**Comment by daveho** [comment]
There were about 900GB free on the hard drive when I got this error.

**Comment by techTrainerHQ** [comment]
A bit late but perhaps your file system didn't allow for such a large fie? I had similar issues when exporting to USB-HDD's.

**Comment by ferdnyc** [comment]
@daveho 

(I realize people are sick of hearing this response, but...) 

OpenShot 2.4.3 is an outdated version, debian haven't updated their package in forever. (Literally **years**. Like 2-3, I think. We've had very little success trying to convince them to update, so far.) 

The current release is OpenShot 2.5.1. It's very very likely the issue you're hitting is fixed in newer builds. You can find AppImage builds of 2.5.1 release and the current development code at https://OpenShot.org/download/

**Comment by ferdnyc** [comment]
Oh, wait, this question itself is 2 years old. Never mind. 😁

**Comment by stratus-ss** [comment]
@ferdnyc should I open a new issue for this? I am having the same problem on 2.5.1 on Arch

**Comment by ferdnyc** [comment]
@stratus-ss Yes, please. There's a bug report form that'll come up when you do, it'll give you some guidance on the information we'd need in order to help.

**Comment by jhite1234** [comment]
@stratus-ss did that new one get anywhere, because I'm still having this issue an additional 2 years later
