### ISSUE TITLE
openshot-qt-2.4.4 fails to start with no module named 'openshot' error

### ISSUE THREAD

**Issue by juanitotc** [OpenShot/openshot-qt#2778]
compiled with:

python3 setup.py build
sudo python3 setup.py install --root=/tmp/pkg

$ openshot-qt
ModuleNotFoundError: No module named 'openshot'

Fixed with:

$ cd /usr/local/lib/python3.6/site-packages
$ sudo ln -s openshot_qt openshot

**Comment by juanitotc** [comment]
Ah - I see the problem, for some reason libopenshot did not install the following:

/usr/local/lib/python3.6/site-packages/_openshot.so
/usr/local/lib/python3.6/site-packages/openshot.py

Now with these the error is fixed

**Comment by cminghao** [comment]
may I know how did you get them to be installed?

**Comment by ferdnyc** [comment]
Normally a `make install` in the libopenshot build dir _should_ install the bindings along with the library itself. Though honestly, that process does a lot of crazy tricks trying to conform to various Linux distributions' ideas about Python package management, and still gets it wrong plenty. At some point that logic will probably end up getting overhauled or ripped out, _again_.
