### ISSUE TITLE
Windows 10 64bit. At the beginning it was working fine, but after a point I cannot insert any video/image. The project files windows stays empty. (Give your bug report a descriptive title)

### ISSUE THREAD

**Issue by y653** [OpenShot/openshot-qt#3307]
**Describe the bug**
Windows 10 64bit. At the beginning it was working fine, but after few days I cannot insert any video/image. The project files windows shows empty. Even though when I close openshot, it asks if I want to save the changes to the project. It seems like the files are added, but not shown at the project files. Thus, I cannot use them. I checked with both 2.5.1 and the latest daily build.

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev2
- Platform: Windows-10-10.0.18362
- Processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['el-GR', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1584748638-2c6d25ee-232f3f79-x86_64.AppImage

**Log Files**
- http://logs.openshot.org/7xuqed8cga96pqeochy9fpgr4gnz1gxq/openshot-qt.zip
- http://logs.openshot.org/7xuqed8cga96pqeochy9fpgr4gnz1gxq/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by ferdnyc** [comment]
Hmm, this sounds like it could be the same bug as #3308. I'll take a look at your logs and see if there are any common threads.

**Comment by ferdnyc** [comment]
Aha. OK, no, the problem here is different.
```
Failed to clear C:\Users\a\.openshot_qt\thumbnail: [WinError 5] Δεν επιτρέπεται η πρόσβαση: 'C:\\Users\\a\\.openshot_qt\\thumbnail'
```
Basically, OpenShot is trying to cache the thumbnails for your video clips in that folder, but it doesn't have access to delete the contents (or, presumably, to create new ones).

There are a few ways you can try to solve this:
1. If you delete `C:\Users\a\.openshot_qt\thumbnail` completely, OpenShot should recreate it. So, assuming it has write permission to the _parent_ folder, that should solve it.
1. You could try copying a small file into the folder. If you can't write there, Windows should offer to change the permissions for you.
1. Or, if you're comfortable managing Windows folder security settings manually, you can right-click on the folder and edit its Properties. You'd want to make sure it's not set read-only, and that your user account has full access.
1. Last but not least, you could delete the **entire** `C:\Users\a\.openshot_qt` directory and let OpenShot recreate it from defaults.

**Comment by y653** [comment]
Thanks! It looks like the same problem. The strange thing is that at the beginning it was working fine with v.2.5.1 and one day it just stopped and up to now it shows the same behaviour. I tried the daily build, and also the portable version (from portableapps.com). The same. I installed the 2.5.1 to a laptop with win10-64bit again, and it works fine!!!

If you have any idea on what to do I would be grateful, because I really liked the features and the interface and I do not want to change to another LNE. Thanks again for your time and efforts!

**Comment by ferdnyc** [comment]
It does actually look like there might be a second problem, as well.
```
HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: http://127.0.0.1:64165/thumbnails/C1JLJIYOXC/1/path/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000015d59cd0>: Failed to establish a new connection: [WinError 10061] Δεν ήταν δυνατή η δημιουργία σύνδεσης, επειδή ο υπολογιστής προορισμού την απέρριψε ενεργά')))
```

To show thumbnails in the interface, OpenShot runs a webserver process that's only reachable from the local system. The Timeline view is web-based, and retrieves the thumbnails from that service. But it looks like the connection isn't getting made on your system.

That _could_ just be because the permission issue prevented the server from ever starting. Or, it could be that the proxy settings are interfering even with connections to the local host (127.0.0.1), (which they shouldn't do). Not sure what can be done about it, if that's the case, it would depend how your local network settings are managed,

**Comment by ferdnyc** [comment]
Hmm. "WinError 10061" is just "Connection refused error", so that's no help at all.

Maybe @SuslikV has some ideas, Windows is more their area.

**Comment by y653** [comment]
I checked the permissions on the folder and they are fine. I have full write access to it. I copy and delete files in it with no problem. I deleted the .openshot_qt directory and it was recreated, but the problem remains. I also run openshot as administrator but nothing changed.

I didn't know that the timeline view was web based. But related to this error, I do not know what to check. Any ideas?

**Comment by SuslikV** [comment]
It looks more like strong security software settings. Maybe add application to some white list?
Windows has build-in firewall - it usually triggers when application is started for the first time (from the new path on the drive), and ask for action to block application or not.

Can you try to install the application to some folder that you have made by yourself (`C:\OpenShot`, for example)? Any changes?

**Comment by y653** [comment]
Well, I finally worked it out!! I write it down for your information and for anyone else that may have the same problem. Actually, the ProxyError above gave me the idea! There was a mess up in the proxy settings after a Windows 10 update. For example I had to change the Firefox network settings few days ago in order to browse websites.

Thus, I followed the advice in this article "[Fix: Unable to connect to Proxy Server in Windows 10](https://appuals.com/unable-to-connect-to-proxy-server-in-windows-10/)", the 2nd method, I deleted the 4 registry entries, rebooted and everything works like a charm now!!!

Thank you so much for your help and your time!
All the best!

**Comment by ferdnyc** [comment]
Glad to hear you tracked down the issue! And, thanks especially for the link. Always appreciated when users share their _solutions_, in addition to their problems. :grin:  I'm sure another user will encounter the same issue at some point, so it'll be great to have some info to point them towards.
