### ISSUE TITLE
Please include mouse options

### ISSUE THREAD

**Issue by CHJ85** [OpenShot/openshot-qt#3393]
Because there are certain things that I wish I could disable or set to keyboard-only shortcuts, like horizontal scrolling for instance.
And also (unrelated). When I hit ctrl+home to set the market at start, it only moves the marker, and not the window slide to the beginning.
Not sure if this is a bug, but would of been nice if you could fix that. Because this is annoying.

**Comment by ferdnyc** [comment]
> Because there are certain things that I wish I could disable or set to keyboard-only shortcuts, like horizontal scrolling for instance.

I'm not sure I follow. Can you give a specific example of the sort of action you'd like to configure, and how?

> And also (unrelated). When I hit ctrl+home to set the market at start, it only moves the marker, and not the window slide to the beginning.

What version of OpenShot are you running, and on what OS? In the current (2.5.1) version, the scroll position should update to follow the playhead when the Prev/Next Marker actions are used.

**Comment by CHJ85** [comment]
Version 2.4.3 on Kubuntu 19.10 (the one from the repo). I tried the flatpak version but that one wouldn't recognize audio codecs and gave me all sorts of errors about video headers and what not. 
Anyway. An example is like when I'm zooming in on the timeline it also scrolls to the side and if I'm mouse scrolling while having the video preferences open, it changes the number value. So stuff like this I wish I'd be able to disable this. The only thing I want scrolling for in Openshot is timeline zooming. Everything else it zooms is super annoying

**Comment by ferdnyc** [comment]
@CHJ85 Thanks, that's helpful.

Well, as I said, some of these issues are fixed in 2.5.1. And, obviously we won't be making any more updates to the 2.4 codebase, so any additional fixes would similarly only be available in 2.5.x or 2.6.x.

(I realize that 2.4.3 is the newest version available in the official Debian/Ubuntu packages, unfortunately we have no control over that, or the flatpak version. We maintain a PPA, actually two — one with the most current release, another with daily snapshot builds. Instructions for both are at https://www.openshot.org/ppa/ . Or, there are the official AppImage builds downloadable at https://www.openshot.org/download/)

Specifically, 2.5.1 addresses:
> When I hit ctrl+home to set the market at start, it only moves the marker, and not the window slide to the beginning.

It also _changes_, somewhat, the timeline zooming:
> when I'm zooming in on the timeline it also scrolls to the side

...Though I'm not sure whether you'll find the new behavior better or worse. What's happening in 2.4.3 is, when you zoom in with the mousewheel, the zoom is centered on your mouse position. So, the timeline doesn't actually scroll sideways, it merely extends itself in both directions _away_ from the mouse pointer. Which, depending where you are on the Timeline, can feel like it's scrolling sideways, especially if the Playhead ends up moving offscreen.

The change we made in 2.5.0/2.5.1 is, now when you zoom — whether it's via the slider, keyboard shortcuts, or +/- toolbar buttons — and your pointer _isn't_ over the Timeline, but the Playhead (red line) is visible in the window, the zoom will be centered on **that** position instead. So, basically the Playhead will appear to remain stationary when zooming, to the extent possible. (The pointer-centered zoom still takes priority when using <kbd>Ctrl</kbd>+wheel over the Timeline, though.)

However, the fact that zooming sometimes alters your scroll position is due to the zoom causing a change in the "size" (effectively) of the Timeline, that's always going to occur to some extent.

That leaves:
> if I'm mouse scrolling while having the video preferences open, it changes the number value.

That's a standard feature of the Qt widgets that our interface is built out of, and actually more generally of XWindows interfaces generally. (You'll typically get that same reactiveness from the spinboxes and combo-boxes (dropdown lists) in pretty much any application running on a Unix — when you hover the pointer over them, you can scroll to change the value.

It's apparently _possible_ to change that default behavior, though it takes [no small amount of work](https://stackoverflow.com/questions/5821802/qspinbox-inside-a-qscrollarea-how-to-prevent-spin-box-from-stealing-focus-when). So, I'll leave this open as a request to make that behavior optional. I really couldn't make any sort of promises as to when or even _if_ that option might be added, though — sorry.

**Comment by CHJ85** [comment]
Thank you for your detailed response.
The new version does fix a lot of these issues. Although, ALT+mousewheel still moves the slide to the left when I zoom in and right when I zoom out.
And I figured out what the problem is. You see. Some window managers use alt+mousewheell for zooming in and out. For me it's the Gnome Shell zoom extension I use when I read stuff. So the zoom shortcut collides with Openshot's slide scroll.
The slider is not under keyboard shortcut settings, and I couldn't find it in the openshot.settings file either.
Do you think you guys could please add this to the keyboard shortcuts settings so I can change it to something else other than alt+mouse wheel?
I can't be the only one having this problem.

**Comment by ferdnyc** [comment]
> Thank you for your detailed response.
> The new version does fix a lot of these issues. Although, ALT+mousewheel still moves the slide to the left when I zoom in and right when I zoom out.
> And I figured out what the problem is. You see. Some window managers use alt+mousewheell for zooming in and out. For me it's the Gnome Shell zoom extension I use when I read stuff. So the zoom shortcut collides with Openshot's slide scroll.

That's the thing, though. OpenShot doesn't _have_ an <kbd>Alt</kbd>+Scroll binding. In fact, I just tested on my Fedora 31 system, and
<kbd>Alt</kbd>+Scroll does nothing at all. 

Our mousewheel-zoom binding is <kbd><b>Ctrl</b></kbd>+Scroll.

I'm not sure where the behavior you're seeing is coming from, but I don't think there's any way we could make something configurable when we don't have any control over it to begin with, sorry.

**Comment by CHJ85** [comment]
Yea. It doesn't seem to be Openshot's fault. But it's weird.
The mousewheel scrolls the timeline up and down, alt+mousewheel scrolls it sideways. But it also zooms in. I disabled the zoom extension (and it is ALT for me, not CTRL. Guess it varies between extensions), and the problem is still there. I thought it was related to the extension. But it still zooms in the timeline and scrolls sideways at the same time.
But it only happens in Openshot, not Kdenlive. I like Openshot better, so I'm not gonna switch video editor over this.
And what a weird behavior. Especially if it's not a preset key binding.
