### ISSUE TITLE
'Reader' error fails to open openshot project in ubuntu 20.04

### ISSUE THREAD

**Issue by nikalakos** [OpenShot/openshot-qt#5008]
After creating a title, opeshot crashed and since then it fails to open the project showing this pop up window. This was not my first title in the project and i can' t imaging what's the problem. I attach photo of the error screen. 
![error](https://user-images.githubusercontent.com/74905045/204479376-9778804d-631d-4710-9c39-716e96e74b71.png)

**Comment by Colorjet3** [comment]
What version of OpenShot are you running and in what operating system environment?

**Comment by nikalakos** [comment]
> What version of OpenShot are you running and in what operating system environment?

version 2.6.0-dev (libopenshot version: 0.2.6-dev) @ ubuntu 20.04 LTS

**Comment by Colorjet3** [comment]
Go to openshot.org/download/#daily and download build #10243 AppImage.  Do NOT download anything newer at this time as there are Export issues that the DEV team is working on.

Run the AppImage and see if that takes care of the issue for you.

**Update:**  The Export issue has been fixed.  Feel free to download the latest DEV Daily Build available.

**Comment by nikalakos** [comment]
> Go to openshot.org/download/#daily and download build #10243 AppImage. Do NOT download anything newer at this time as there are Export issues that the DEV team is working on.
> 
> Run the AppImage and see if that takes care of the issue for you.
> 
> **Update:** The Export issue has been fixed. Feel free to download the latest DEV Daily Build available.

The problem still exists even though i did what you adviced me.

**Comment by Colorjet3** [comment]
You probably have a corrupt project. 

1. There have been many updates since build #10243.  Please download the latest DEV Daily Build available.
2. Don't start OpenShot yet.
3. Backup /home/username/.openshot_qt folder.
4. Delete /home/username/.openshot_qt folder.
5. Start OpenShot and try recreating your project.
6. If still having issues, please provide a step-by-step instructions as to what you are doing so we can try and replicate your issue.

**Comment by Colorjet3** [comment]
No Response.
