### ISSUE TITLE
OpenShot AppImage not starting / glibc error

### ISSUE THREAD

**Issue by hannob** [OpenShot/openshot-qt#5182]
**Describe the bug:**
When I try to start the AppImage I get an error like this:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/cx_Freeze/initscripts/__startup__.py", line 40, in run
  File "/usr/local/lib/python3.8/dist-packages/cx_Freeze/initscripts/Console.py", line 37, in run
  File "openshot_qt/launch.py", line 55, in <module>
    from PyQt5.QtWidgets import QApplication
ImportError: /tmp/.mount_OpenSh0MSKxT/usr/bin/libm.so.6: version `GLIBC_2.35' not found (required by /usr/lib64/libharfbuzz.so.0)
```
This happens with the 3.0.0 release, the 3.1.0 release candidate and the daily build.

**Steps to reproduce the behavior:**

Download appimage and try to execute.

**Expected behavior:**
OpenShot should start. but does not.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: 3.0.0, 3.0.0-daily-11120, 3.1.0-release-candidate-11128
- Operating System / Distro: Gentoo Linux (glibc 2.37)

**Comment by ralosch** [comment]
Same her on openSuse Tumbleweed
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/cx_Freeze/initscripts/__startup__.py", line 40, in run
  File "/usr/local/lib/python3.8/dist-packages/cx_Freeze/initscripts/Console.py", line 37, in run
  File "openshot_qt/launch.py", line 55, in <module>
    from PyQt5.QtWidgets import QApplication
ImportError: /tmp/.mount_OpenSh5foSdr/usr/bin/libm.so.6: version `GLIBC_2.35' not found (required by /lib64/libharfbuzz.so.0)

glibc 2.37

**Comment by mamyn0va** [comment]
Same here on manjaro with glibc2.37.

```
./OpenShot-v3.0.0-x86_64.AppImage
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/cx_Freeze/initscripts/__startup__.py", line 40, in run
  File "/usr/local/lib/python3.8/dist-packages/cx_Freeze/initscripts/Console.py", line 37, in run
  File "openshot_qt/launch.py", line 55, in <module>
    from PyQt5.QtWidgets import QApplication
ImportError: /tmp/.mount_OpenShmN8r7G/usr/bin/libm.so.6: version `GLIBC_2.35' not found (required by /usr/lib/libharfbuzz.so.0)
```

![screenshot_2023-03-28T23:54:59](https://user-images.githubusercontent.com/11281228/228376078-6c111fec-c0ff-4fea-9e62-b89fab5f3b80.png)

**Comment by cspyc** [comment]
Same here on Linux Mint 19.2 Tina  with glibc2.28

./OpenShot-v3.1.0-release-candidate-11189-18328995-8eb23127-x86_64.AppImage
/tmp/.mount_OpenShvgxDJG/usr/bin/openshot-qt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_OpenShvgxDJG/usr/bin/lib/libpython3.8.so.1.0)

**Comment by jonoomph** [comment]
Older distros, with glibc versions earlier than 2.31 are not compatible with our current AppImages. However, older AppImages might still work (as a work-around). The best approach for older distros (with < 2.31 glibc) should install from source, or find an updated repository built from the latest source code - and thus, it will be built against your current version of glibc.

For newer versions of glibc, including 2.35, our latest daily build or release candidates (AppImage) from https://www.openshot.org/download#daily "should" be fully compatible. For example, I just tested on Ubuntu 22.04 (running glibc 2.35) and the AppImage works fine.

I have not tested on systems which require glibc 2.37 yet... and I will do that today, and see if I run into any issues. I'll keep you posted.

**Comment by jonoomph** [comment]
I was able to successfully reproduce the crash with glibc 2.37 (using Manjaro 22) and our latest daily AppImage. I also found a very relevant article about the issue with `libharfbuzz`: https://github.com/AppImageCommunity/pkg2appimage/issues/352 and https://github.com/harfbuzz/harfbuzz/issues/3216. I do not currently have a solution for this, but I'm open to suggestions.

**Comment by sullyj3** [comment]
I have the same issue trying to run the daily build on Arch
```
⮞ pacman -Qi glibc|rg version
Version         : 2.37-3
⮞ ./OpenShot-v3.1.1-x86_64.AppImage
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/cx_Freeze/initscripts/__startup__.py", line 40, in run
  File "/usr/local/lib/python3.8/dist-packages/cx_Freeze/initscripts/Console.py", line 37, in run
  File "openshot_qt/launch.py", line 55, in <module>
    from PyQt5.QtWidgets import QApplication
ImportError: /tmp/.mount_OpenSh661Y6s/usr/bin/libm.so.6: version `GLIBC_2.35' not found (required by /usr/lib/libharfbuzz.so.0)
```

The reason I'm trying the daily appimage is that I'm running into #5239 with the one in the arch repos

**Comment by Mark-Alford** [comment]
Same here on fully updated Fedora 38 with glibc 2.37
`Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/cx_Freeze/initscripts/__startup__.py", line 40, in run
  File "/usr/local/lib/python3.8/dist-packages/cx_Freeze/initscripts/Console.py", line 37, in run
  File "openshot_qt/launch.py", line 55, in <module>
    from PyQt5.QtWidgets import QApplication
ImportError: /tmp/.mount_OpenShBPYTaC/usr/bin/libm.so.6: version `GLIBC_2.35' not found (required by /lib64/libharfbuzz.so.0)
`

**Comment by drevoborod** [comment]
> I was able to successfully reproduce the crash with glibc 2.37 (using Manjaro 22) and our latest daily AppImage. ... I do not currently have a solution for this, but I'm open to suggestions.

Isn't it an option just to include required glibc binary into AppImage? Or even all necessary C binaries?

**Comment by Bert-H** [comment]
Same issue here with Fedora38, glibc version 2.37, using latest Daily Build 11529:

./OpenShot-v3.1.1-daily-11529-95eccafc-08c2cdd1-x86_64.AppImage
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/cx_Freeze/initscripts/__startup__.py", line 40, in run
  File "/usr/local/lib/python3.8/dist-packages/cx_Freeze/initscripts/Console.py", line 37, in run
  File "openshot_qt/launch.py", line 55, in <module>
    from PyQt5.QtWidgets import QApplication
ImportError: /tmp/.mount_OpenSh6ptX7T/usr/bin/libm.so.6: version `GLIBC_2.35' not found (required by /lib64/libharfbuzz.so.0)

Note that for me this issue started after upgrading from Fedora37, which had glibc 2.36.

**Comment by Bert-H** [comment]
I've also posted the below under new issue #5300. Hope it will be of help to someone.

PROBLEM
Openshot fails to start on Fedora38 with error:

./OpenShot-v3.1.1-daily-11556-95eccafc-08c2cdd1-x86_64.AppImage
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/cx_Freeze/initscripts/__startup__.py", line 40, in run
  File "/usr/local/lib/python3.8/dist-packages/cx_Freeze/initscripts/Console.py", line 37, in run
  File "openshot_qt/launch.py", line 55, in <module>
    from PyQt5.QtWidgets import QApplication
ImportError: /tmp/.mount_OpenShmAfqet/usr/bin/libm.so.6: version `GLIBC_2.35' not found (required by /lib64/libharfbuzz.so.0)

WORKAROUND

Firstly, "libharfbuzz" is also used by other applications such as LibreOffice.
LibreOffice works fine so there is some difference between the Openshot image and LibreOffice.
As can be seen in the error message, the file in the Openshot appimage causing the issue is "/$PATH/usr/bin/libm.so.6".
On Fedora itself, this file is located in "/lib64/". This file is more recent than the one in the Openshot appimage.
To look at the files in the Openshot appimage run:
"./OpenShot-v3.1.1-daily-11556-95eccafc-08c2cdd1-x86_64.AppImage --appimage-extract".
This will extract the files to the "$YOUR-PATH/squashfs-root" directory. "libm.so.6" is in squashfs-root/usr/bin/.

What worked for me is to replace "libm.so.6" in the Appimage with the version in "/lib64" on Fedora and then re-packaging the appimage again by using "appimagetool".
"appimagetool" can be downloaded for your platform here:
https://github.com/AppImage/appimagetool/releases/tag/continuous
"appimagetool" is an appimage itself so there is nothing to install. Just make executable and run.

To repackage the Openshot appimage after replacing the file, run:
"./appimagetool-x86_64.AppImage -v /$YOUR-PATH/squashfs-root"
This creates the file "OpenShot_Video_Editor-x86_64.AppImage" in $YOUR-PATH
Run the appimage as per usual.

Tested it by creating a small project, previewing and exporting it. All worked fine.
More thorough testing may show an issue. Time will tell, fingers crossed.
An error message that can be seen in the "openshot-qt.log" file is a mis-match in the SHA hash.

Again, this worked for me on Fedora38. Not sure if it will work on other platforms.

**Comment by tbocek** [comment]
> Again, this worked for me on Fedora38. Not sure if it will work on other platforms.

Works with Arch Linux as well

**Comment by cytech** [comment]
also worked with ubuntu 23.10

**Comment by Fabioamd87** [comment]
guys is there any update for this bug?

**Comment by Colorjet3** [comment]
Hello @Fabioamd87.  Not that I am aware of.  Have you tried installing using the PPA installation?  You can find it here:  https://www.openshot.org/ppa/.  I recommend you run the Daily PPA.

**Comment by Fabioamd87** [comment]
Hello @Colorjet3 thanks it looks like a good solution.
Do you know if PPA works also with the newly released Ubuntu 23.10?

**Comment by Colorjet3** [comment]
Hello @Fabioamd87.  I am in the process of installing Ubuntu 23.10 in my virtual environment to test.  Will update you shortly.

**Comment by Fabioamd87** [comment]
Hello @Colorjet3 , thanks a lot for your availability.

**Comment by Colorjet3** [comment]
You are welcome @Fabioamd87.  I just installed Ubuntu 23.10.1.  I performed the PPA installation and I noticed that it installed OpenShot v2.6.1.  Something is broken with the Daily Build installation of v3.1.1.  Nothing I can do about this since the lead developer has to look into it.

I then downloaded the v3.1.1 AppImage and that doesn't run either.  Need to troubleshoot this.

I have not tried running the production PPA installation.

I don't have time right now to debug but will work on it later this evening.

**Update:**  The Stable PPA installation instructions is also pointing to v2.6.1.  I have left a message with the lead developer at this time.

**Comment by Fabioamd87** [comment]
Thanks a lot, I hope my observation has been useful to fix these issues.
Let me know if I there is something I can test on my side as well.

**Comment by Colorjet3** [comment]
Hello @Fabioamd87.  I haven't found a fix.  Please check the workaround by @Bert-H from August 13 response in this thread.  I am a novice Linux user and got stuck on running the appimagetool to create a new Openshot AppImage file.  May be you can figure it out.

However, what worked for me, per user Bert-H's instructions is:
1. Download and extract the image.
2. Make it Executable.
3. Now extract the AppImage file:  "./OpenShot-v3.1.1-daily-11556-95eccafc-08c2cdd1-x86_64.AppImage --appimage-extract"

This will extract the files to the "$YOUR-PATH/squashfs-root" directory. "libm.so.6" is in squashfs-root/usr/bin/.

6. Now navigate to "$YOUR-PATH/squashfs-root".
7. Override the libm.so.6 file in OpenShot with the one from your system (Ubuntu).
8. Find the "AppRun", right click it and select "Run".

**Hint:**  I found libm.so.6 in /usr/lib/x86_64-linux-gnu.  This is what I used to override what comes in the OpenShot AppImage.

**Comment by Fabioamd87** [comment]
thanks, it works!
Procedure for Ubuntu 23.10:

```
$ wget https://github.com/OpenShot/openshot-qt/releases/download/v3.1.1/OpenShot-v3.1.1-x86_64.AppImage
$ chmod +x OpenShot-v3.1.1-x86_64.AppImage
$ ./OpenShot-v3.1.1-x86_64.AppImage --appimage-extract
$ sudo cp /usr/lib/x86_64-linux-gnu/libm.so.6 squashfs-root/usr/bin/
```

hope for an easier process to run it :)

**Comment by JamesRichards22** [comment]
@Colorjet3 I just opened #5360. If you're still getting a 2.x version then it's not installing the version from the PPA correctly and using the Ubuntu default version. (I was about to open a second issue about the AppImage but saw this.)

**Comment by esklarski** [comment]
The AppImage doesn't work on Fedora 39.

But the Flathub version works fine so that's a good solution in my mind.

**Comment by chrisawi** [comment]
This is happening because you have harfbuzz from the host using a bundled copy of libm that is older that the version it was built against. The solution would be to not bundle `libm.so.6`.

At a glance, it looks like it can be excluded here with the rest of glibc: https://github.com/OpenShot/openshot-qt/blob/develop/freeze.py#L368

**Comment by Colorjet3** [comment]
Hello @jonoomph.  You may want to take a look at this.

**Comment by citadel-lewis** [comment]
I've tried adding the PPA for latest release of Ubuntu but there are no releases for in the OpenShot PPA for Mantic - will these be added soon?

**Comment by Colorjet3** [comment]
> I've tried adding the PPA for latest release of Ubuntu but there are no releases for in the OpenShot PPA for Mantic - will these be added soon?

Hello @jonoomph.  This needs your attention.

**Comment by Colorjet3** [comment]
A new daily build has been release to address this issue.  Please go to openshot.org/download/#daily and download the AppImage build #11732 and give it a try.

I tested this in Ubuntu 23.10 & Fedora 39 without any startup issues.

**Comment by jonoomph** [comment]
Fixed in https://github.com/OpenShot/openshot-qt/pull/5423

**Comment by Fabioamd87** [comment]
Thanks, it seems to work now!

**Comment by Bert-H** [comment]
Yes, working too now on FC39. Thanks Jonathan for your efforts!

**Comment by RafaelLinux** [comment]
This error is still present in AppImage version 3.1.1
```

 ./OpenShot.AppImage                                                                                                                                       1
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/cx_Freeze/initscripts/__startup__.py", line 40, in run
  File "/usr/local/lib/python3.8/dist-packages/cx_Freeze/initscripts/Console.py", line 37, in run
  File "openshot_qt/launch.py", line 55, in <module>
    from PyQt5.QtWidgets import QApplication
ImportError: /tmp/.mount_OpenSh2vQoPP/usr/bin/libm.so.6: version `GLIBC_2.35' not found (required by /lib64/libharfbuzz.so.0)
```

Why still not fixed?? I use a lot of AppImage applications and they runs w/o issues!!!

**Comment by Colorjet3** [comment]
Hello @RafaelLinux .  Are you running the latest DEV Daily Build AppImage?  This was fixed in the latest dev daily build.

Go to openshot.org/download/#daily and download the latest dev daily build AppImage available and give that a try.

**Comment by RafaelLinux** [comment]
No. I didn't know there existed a DEV version. I tried and error is gone.

THANK YOU and my compliments for an IMMEDIATE response. That's a pleasure.

**Comment by Colorjet3** [comment]
You are welcome @RafaelLinux .  It is all about timing and I just happened to be online and saw your post.

Glad it is working for you now.  A production release is coming soon that will have this fix and other fixes and enhancements as well.
