### ISSUE TITLE
freezing right after opening

### ISSUE THREAD

**Issue by atadolfo** [OpenShot/openshot-qt#5213]
**Describe the bug**
The application freezing right after opening. Can't click on anything after opening

**Steps to reproduce the behavior:**
1. Open the application :D

**Expected behavior**
Not freezing, lol

**System Details**
- OpenShot Version: 3.1.0
- libopenshot Version:  0.3.1
- Platform: Windows-10-10.0.22621
- Processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['pt-BR', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.1.0-daily-11349-96650934-0884bd96-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/ovvuh5v51krhj0bpt8tmkf7cxklaah2s/openshot-qt.zip) (4 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Capturas de Ecrã** (Optional)
![image](https://user-images.githubusercontent.com/17051400/232380885-a8d1db96-d511-4ef4-a5f0-4746c18fa711.png)

**Comment by Colorjet3** [comment]
Hello @atadolfo.  This issue has been fixed in the latest DEV Daily Build. 

1.  Please go to openshot.org/download/#daily and download the latest DEV Daily Build available.
2.  Make a backup of c:\users\username\.openshot_qt folder.
3.  Delete c:\users\username\.openshot_qt folder.
4.  Install the latest DEV Daily Build.

Let us know if this resolved your issue.

**Comment by Sidder3** [comment]
OpenShot-v3.1.1-release-candidate-11371 still has this issue for me.

Workaround provided in post #5195 (now closed) works well and Openshot starts normally.

**Comment by Colorjet3** [comment]
Hello @Sidder3.  Just to confirm that after you changed the sample rate to 48000 in Openshot, then the problem went away.

Is this correct?

Also, when you have the freeze after opening, it seems that Openshot is still responsive enough that you can go into Edit | Preferences and change the sample rate.  Is this your experience or did you do something else to change the sample rate?

Any other details you can provide?  This is critical as the DEV team is getting ready to publish a new release and we are just about to get started with Release-Candidate testing (pre-production Release testing).  I really would like to see this issue taken care of before Production release.

Thank you in advance!

**Update:**  
Going way too fast.  I now know that after you freeze, you force close Openshot and update the sample rate in openshot.settings files.  If you can tell me what the default is set to before you change it that would be great.

**Comment by Sidder3** [comment]
@Colorjet3 Hello!

Yes it is correct, I have manipulated openshot.settings file. 
I have set sample rate to 96000 (to match my sound device)
Default, mentioned in the file was 48000

**EDIT:** Just checked latest RC 11380 from 17/04 - problem still there.
Again changed sample rate in openshot.settings - and software starts normally.

Made a screenshot of default settings for you:

![Screenshot 2023-04-18 185942](https://user-images.githubusercontent.com/122721917/232851251-b3e73315-c4a2-4111-b63a-42ac62162f70.png)


Hope this helps!

**Comment by Colorjet3** [comment]
Thank you @Sidder3 for all the information.  Yes, we are seeing the same issue and behavior.  The lead developer is working on a resolution.

**Comment by Colorjet3** [comment]
Hello @Sidder3.   Wanted to let you know that v3.1.1-Release-Candidate-11382 now has the fix for the freezing issue at startup.

It would be great if you want to give it a test and let me know how it went:
1.  Go to openshot.org/download/#daily.
2.  Download build #11382.
3.  Close Openshot if running.
4.  Backup c:\users\username\.openshot_qt folder.
5.  Delete c:\users\username\.openshot_qt folder.
6.  Install the build #11382 and start it.
7.  Did Openshot start without freezing?

Thank you!

**Comment by atadolfo** [comment]
The stable version works fine
