### ISSUE TITLE
Openshot 2.3.3 crashes when add an audio track

### ISSUE THREAD

**Issue by Interspock** [OpenShot/openshot-qt#657]
**System Details:**
* Operating System / Distro: Linux Mint 17.3 64 bits
* OpenShot Version: 2.3.3
* Logs (libopenshot.log and openshot-qt.log) included in logs.zip

New issue after upgrading 2.3.3: 

Openshot crashes when adding audio (mp3) track to the timeline OR when I preview an audio track in the project files drawer  

[logs.zip](https://github.com/OpenShot/openshot-qt/files/1014187/logs.zip)

**Comment by axmoran** [comment]
I am having a similar issue.  It's working fine when I load videos, but unable to add an MP3 file.

Operating system:  Windows 10
OpenShot Version: 2.3.3

**Comment by vales** [comment]
I also have the same problem when I insert an audio file on a track.

Windows 10 64bit
Openshot 2.3.3.

**Comment by Interspock** [comment]
Unfortunately it's unusable the program with this bug.. :( openshot closes immediately I add a sound file in the timeline

**Comment by antaenc** [comment]
Same! With AC3 file. Can add it, won't play/preview. Immediate crash.

Ubuntu 16.04
Openshot 2.3.3

`Caught signal 11 (SIGSEGV)
---- Unhandled Exception: Stack Trace ----
---- End of Stack Trace ----
QObject::~QObject: Timers cannot be stopped from another thread
QSocketNotifier: Invalid socket 16 and type 'Read', disabling...
QSocketNotifier: Invalid socket 34 and type 'Read', disabling...
QSocketNotifier: Invalid socket 66 and type 'Read', disabling...
Caught signal 11 (SIGSEGV)
---- Unhandled Exception: Stack Trace ----
  /lib/x86_64-linux-gnu/libglib-2.0.so.0 (                                           + 0x4a330)  [0x7fcee0dc5330]
  /lib/x86_64-linux-gnu/libglib-2.0.so.0 ( g_main_context_iteration                  + 0x2c  )  [0x7fcee0dc549c]
  /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 ( QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>)  + 0x7b  )  [0x7fcee193d7eb]
  /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 ( QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>)  + 0x10a )  [0x7fcee18e4b4a]
  /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 ( QCoreApplication::exec()                  + 0x9c  )  [0x7fcee18ecbec]
  /usr/lib/python3/dist-packages/PyQt5/QtWidgets.cpython-35m-x86_64-linux-gnu.so (                                           + 0x14e0bb)  [0x7fcee285a0bb]
  /usr/bin/python3               ( PyCFunction_Call                          + 0x4f  )  [0x4e9b9f]
  /usr/bin/python3               ( PyEval_EvalFrameEx                        + 0x614 )  [0x524414]
  /usr/bin/python3               ( PyEval_EvalFrameEx                        + 0x4a14)  [0x528814]
  /usr/bin/python3               ( PyEval_EvalFrameEx                        + 0x4a14)  [0x528814]
  /usr/bin/python3               (                                                   )  [0x52d2e3]
  /usr/bin/python3               ( PyEval_EvalCode                           + 0x1f  )  [0x52dfdf]
  /usr/bin/python3               (                                                   )  [0x5fd2c2]
  /usr/bin/python3               ( PyRun_FileExFlags                         + 0x9a  )  [0x5ff76a]
  /usr/bin/python3               ( PyRun_SimpleFileExFlags                   + 0x1bc )  [0x5ff95c]
  /usr/bin/python3               ( Py_Main                                   + 0x456 )  [0x63e7d6]
  /usr/bin/python3               ( main                                      + 0xe1  )  [0x4cfe41]
  /lib/x86_64-linux-gnu/libc.so.6 ( __libc_start_main                         + 0xf0  )  [0x7fcee5422830]
  /usr/bin/python3               ( _start                                    + 0x29  )  [0x5d5f29]
---- End of Stack Trace ----
`

**Comment by enoversum** [comment]
+1. Wanted to try it out for the first time, added one video, tried to add an audio file in various formats (Wave/FLAC/MP3), imported it then, added to timeline -> crashes. Not the best start for a relationship with OpenShot :( .

**Comment by SunDancerGE** [comment]
Same here. Trying to add mp3 ends in "launch.exe" crash

System Details:

-     Operating System Windows 7 Pro 64 bit
-     OpenShot Version: 2.3.3

**Comment by Decoherent** [comment]
Here's another log: (sorry, I've posted to two of these threads, I didn't see the oldest)
[openshot-qt.zip](https://github.com/OpenShot/openshot-qt/files/1027961/openshot-qt.zip)

**Comment by frozenjava** [comment]
Same issue on OSX 10.11.6

**Comment by vovech** [comment]
Same Issue on Windows 10, V 2.3.3

**Comment by luismgallegosc** [comment]
Same issue on Linux Mint Cinammon 18.1, v2.3.3

**Comment by jabi27** [comment]
Same issue on ubuntu 17.04 
...
...
preview_thread:INFO refreshFrame
preview_thread:INFO self.player.Position(): 1
**[AudioData @ 0x7f74dc0d86f0] invalid NULL pointer for src[0]**
timeline_webview:INFO UpdateLayerIndex
 main_window:INFO updateStatusChanged
 main_window:INFO updateStatusChanged
...
..
/Jan

**Comment by B94** [comment]
I tried the latest dev build (2,3,3-dev2) from the daily builds but it still crashes. I'm running Windows 10

**Comment by ranticpanel** [comment]
Same issue here

**Comment by pybiter** [comment]
Also crashes when adding an aiff file to the timeline

Caught signal 11 (SIGSEGV)
---- Unhandled Exception: Stack Trace ----
QLibraryPrivate::unload succeeded on "/tmp/.mount_QoD7rR/usr/bin/imageformats/libqgif.so"  
QLibraryPrivate::unload succeeded on "/tmp/.mount_QoD7rR/usr/bin/imageformats/libqico.so"  
QLibraryPrivate::unload succeeded on "/tmp/.mount_QoD7rR/usr/bin/imageformats/libqjpeg.so"  
QLibraryPrivate::unload succeeded on "/tmp/.mount_QoD7rR/usr/bin/imageformats/libqsvg.so"  
  /tmp/.mount_QoD7rR/usr/bin/libQt5Core.so.5 ( QVariant::cmp(QVariant const&) const      + 0x146 )  [0x7fa587917e66]
  /tmp/.mount_QoD7rR/usr/bin/libQt5Gui.so.5 ( QStandardItem::setData(QVariant const&, int)  + 0x1b7 )  [0x7fa58808ffc7]
  /tmp/.mount_QoD7rR/usr/bin/PyQt5.QtGui.so (                                           + 0x1041e2)  [0x7fa581f771e2]
  /tmp/.mount_QoD7rR/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalFrameEx                        + 0x6d79)  [0x7fa58ba6b819]
  /tmp/.mount_QoD7rR/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalCodeEx                         + 0x886 )  [0x7fa58bb9c1c6]
  /tmp/.mount_QoD7rR/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalFrameEx                        + 0x6742)  [0x7fa58ba6b1e2]
  /tmp/.mount_QoD7rR/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalCodeEx                         + 0x886 )  [0x7fa58bb9c1c6]
  /tmp/.mount_QoD7rR/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalFrameEx                        + 0x6742)  [0x7fa58ba6b1e2]
  /tmp/.mount_QoD7rR/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalFrameEx                        + 0x6c5c)  [0x7fa58ba6b6fc]
  /tmp/.mount_QoD7rR/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalFrameEx                        + 0x6c5c)  [0x7fa58ba6b6fc]
  /tmp/.mount_QoD7rR/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalCodeEx                         + 0x886 )  [0x7fa58bb9c1c6]
  /tmp/.mount_QoD7rR/usr/bin/libpython3.4m.so.1.0 (                                           + 0x2237f6)  [0x7fa58bb9c7f6]
  /tmp/.mount_QoD7rR/usr/bin/libpython3.4m.so.1.0 ( PyObject_Call                             + 0x68  )  [0x7fa58bab6938]
  /tmp/.mount_QoD7rR/usr/bin/libpython3.4m.so.1.0 (                                           + 0x1167dd)  [0x7fa58ba8f7dd]
  /tmp/.mount_QoD7rR/usr/bin/libpython3.4m.so.1.0 ( PyObject_Call                             + 0x68  )  [0x7fa58bab6938]
  /tmp/.mount_QoD7rR/usr/bin/libpython3.4m.so.1.0 ( PyEval_CallObjectWithKeywords             + 0x47  )  [0x7fa58bb5aba7]
  /tmp/.mount_QoD7rR/usr/bin/PyQt5.QtCore.so ( PyQtSlot::invoke(_object*, _object*) const  + 0x50  )  [0x7fa5825b0360]
  /tmp/.mount_QoD7rR/usr/bin/PyQt5.QtCore.so ( PyQtSlot::invoke(void**, _object*, void*) const  + 0xcf  )  [0x7fa5825b07cf]
  /tmp/.mount_QoD7rR/usr/bin/PyQt5.QtCore.so (                                           + 0x1e85df)  [0x7fa5825ae5df]
  /tmp/.mount_QoD7rR/usr/bin/PyQt5.QtCore.so ( qpycore_qobject_qt_metacall(_sipSimpleWrapper*, _sipTypeDef*, QMetaObject::Call, int, void**)  + 0x42  )  [0x7fa5825ae6b2]
  /tmp/.mount_QoD7rR/usr/bin/libQt5WebKit.so.5 (                                           + 0x6c6cb9)  [0x7fa57c849cb9]
  /tmp/.mount_QoD7rR/usr/bin/libQt5WebKit.so.5 (                                           + 0x1544ea4)  [0x7fa57d6c7ea4]
  /tmp/.mount_QoD7rR/usr/bin/libQt5WebKit.so.5 (                                           + 0x16d3fa0)  [0x7fa57d856fa0]
  [0x7fa50bfff1cb]                        
---- End of Stack Trace ----
Caught signal 11 (SIGSEGV)
---- Unhandled Exception: Stack Trace ----
QLibraryPrivate::unload succeeded on "/tmp/.mount_QoD7rR/usr/bin/platforms/libqxcb.so"  
[1]    24769 segmentation fault (core dumped)  ./OpenShot-v2.3.3-x86_64.AppImage

**Comment by leegold** [comment]
Linux Mint 17.3, ver 2.33
Is this related bug? 
I put .ogg small audio file into timeline and play it. At end of playing it crashes everytime, terminal output below:

Caught signal 11 (SIGSEGV)
---- Unhandled Exception: Stack Trace ----
properties_model:INFO Update frame to 143
properties_model:INFO updating clip properties model.
properties_model:INFO Getting properties for frame 143: OrderedDict([('alpha', {'closest_point_x': 1.0, 'max': 1.0, 'name': 'Alpha', 'interpolation': 2, 'value': 1.0, 'points': 1, 'min': 0.0, 'previous_point_x': 1.0, 'type': 'float', 'keyframe': False, 'choices': [], 'memo': '', 'readonly': False}), ('anchor', {'closest_point_x': -1, 'max': 1.0, 'name': 'Anchor', 'interpolation': 2, 'value': 0.0, 'points': 0, 'min': 0.0, 'previous_point_x': -1, 'type': 'int', 'keyframe': False, 'choices': [{'value': 0, 'selected': True, 'name': 'Canvas'}, {'value': 1, 'selected': False, 'name': 'Viewport'}], 'memo': '', 'readonly': False}), ('channel_filter', {'closest_point_x': 1.0, 'max': 10.0, 'name': 'Channel Filter', 'interpolation': 2, 'value': -1.0, 'points': 1, 'min': -1.0, 'previous_point_x': 1.0, 'type': 'int', 'keyframe': False, 'choices': [], 'memo': '', 'readonly': False}), ('channel_mapping', {'closest_point_x': 1.0, 'max': 10.0, 'name': 'Channel Mapping', 'interpolation': 2, 'value': -1.0, 'points': 1, 'min': -1.0, 'previous_point_x': 1.0, 'type': 'int', 'keyframe': False, 'choices': [], 'memo': '', 'readonly': False}), ('duration', {'closest_point_x': -1, 'max': 5184000.0, 'name': 'Duration', 'interpolation': 2, 'value': 5.921103954315186, 'points': 0, 'min': 0.0, 'previous_point_x': -1, 'type': 'float', 'keyframe': False, 'choices': [], 'memo': '', 'readonly': True}), ('has_audio', {'closest_point_x': 1.0, 'max': 1.0, 'name': 'Enable Audio', 'interpolation': 2, 'value': -1.0, 'points': 1, 'min': -1.0, 'previous_point_x': 1.0, 'type': 'int', 'keyframe': False, 'choices': [], 'memo': '', 'readonly': False}), ('has_video', {'closest_point_x': 1.0, 'max': 1.0, 'name': 'Enable Video', 'interpolation': 2, 'value': -1.0, 'points': 1, 'min': -1.0, 'previous_point_x': 1.0, 'type': 'int', 'keyframe': False, 'choices': [], 'memo': '', 'readonly': False}), ('end', {'closest_point_x': -1, 'max': 5184000.0, 'name': 'End', 'interpolation': 2, 'value': 5.921103954315186, 'points': 0, 'min': 0.0, 'previous_point_x': -1, 'type': 'float', 'keyframe': False, 'choices': [], 'memo': '', 'readonly': False}), ('display', {'closest_point_x': -1, 'max': 3.0, 'name': 'Frame Number', 'interpolation': 2, 'value': 0.0, 'points': 0, 'min': 0.0, 'previous_point_x': -1, 'type': 'int', 'keyframe': False, 'choices': [{'value': 0, 'selected': True, 'name': 'None'}, {'value': 1, 'selected': False, 'name': 'Clip'}, {'value': 2, 'selected': False, 'name': 'Timeline'}, {'value': 3, 'selected': False, 'name': 'Both'}], 'memo': '', 'readonly': False}), ('gravity', {'closest_point_x': -1, 'max': 8.0, 'name': 'Gravity', 'interpolation': 2, 'value': 4.0, 'points': 0, 'min': 0.0, 'previous_point_x': -1, 'type': 'int', 'keyframe': False, 'choices': [{'value': 0, 'selected': False, 'name': 'Top Left'}, {'value': 1, 'selected': False, 'name': 'Top Center'}, {'value': 2, 'selected': False, 'name': 'Top Right'}, {'value': 3, 'selected': False, 'name': 'Left'}, {'value': 4, 'selected': True, 'name': 'Center'}, {'value': 5, 'selected': False, 'name': 'Right'}, {'value': 6, 'selected': False, 'name': 'Bottom Left'}, {'value': 7, 'selected': False, 'name': 'Bottom Center'}, {'value': 8, 'selected': False, 'name': 'Bottom Right'}], 'memo': '', 'readonly': False}), ('id', {'closest_point_x': -1, 'max': -1.0, 'name': 'ID', 'interpolation': 2, 'value': 0.0, 'points': 0, 'min': -1.0, 'previous_point_x': -1, 'type': 'string', 'keyframe': False, 'choices': [], 'memo': '127EJM19B2', 'readonly': True}), ('location_x', {'closest_point_x': 1.0, 'max': 1.0, 'name': 'Location X', 'interpolation': 2, 'value': 0.0, 'points': 1, 'min': -1.0, 'previous_point_x': 1.0, 'type': 'float', 'keyframe': False, 'choices': [], 'memo': '', 'readonly': False}), ('location_y', {'closest_point_x': 1.0, 'max': 1.0, 'name': 'Location Y', 'interpolation': 2, 'value': 0.0, 'points': 1, 'min': -1.0, 'previous_point_x': 1.0, 'type': 'float', 'keyframe': False, 'choices': [], 'memo': '', 'readonly': False}), ('position', {'closest_point_x': -1, 'max': 5184000.0, 'name': 'Position', 'interpolation': 2, 'value': 0.0, 'points': 0, 'min': 0.0, 'previous_point_x': -1, 'type': 'float', 'keyframe': False, 'choices': [], 'memo': '', 'readonly': False}), ('rotation', {'closest_point_x': 1.0, 'max': 360.0, 'name': 'Rotation', 'interpolation': 2, 'value': 0.0, 'points': 1, 'min': -360.0, 'previous_point_x': 1.0, 'type': 'float', 'keyframe': False, 'choices': [], 'memo': '', 'readonly': False}), ('scale', {'closest_point_x': -1, 'max': 3.0, 'name': 'Scale', 'interpolation': 2, 'value': 1.0, 'points': 0, 'min': 0.0, 'previous_point_x': -1, 'type': 'int', 'keyframe': False, 'choices': [{'value': 0, 'selected': False, 'name': 'Crop'}, {'value': 1, 'selected': True, 'name': 'Best Fit'}, {'value': 2, 'selected': False, 'name': 'Stretch'}, {'value': 3, 'selected': False, 'name': 'None'}], 'memo': '', 'readonly': False}), ('scale_x', {'closest_point_x': 1.0, 'max': 1.0, 'name': 'Scale X', 'interpolation': 2, 'value': 1.0, 'points': 1, 'min': 0.0, 'previous_point_x': 1.0, 'type': 'float', 'keyframe': False, 'choices': [], 'memo': '', 'readonly': False}), ('scale_y', {'closest_point_x': 1.0, 'max': 1.0, 'name': 'Scale Y', 'interpolation': 2, 'value': 1.0, 'points': 1, 'min': 0.0, 'previous_point_x': 1.0, 'type': 'float', 'keyframe': False, 'choices': [], 'memo': '', 'readonly': False}), ('shear_x', {'closest_point_x': 1.0, 'max': 1.0, 'name': 'Shear X', 'interpolation': 2, 'value': 0.0, 'points': 1, 'min': -1.0, 'previous_point_x': 1.0, 'type': 'float', 'keyframe': False, 'choices': [], 'memo': '', 'readonly': False}), ('shear_y', {'closest_point_x': 1.0, 'max': 1.0, 'name': 'Shear Y', 'interpolation': 2, 'value': 0.0, 'points': 1, 'min': -1.0, 'previous_point_x': 1.0, 'type': 'float', 'keyframe': False, 'choices': [], 'memo': '', 'readonly': False}), ('start', {'closest_point_x': -1, 'max': 5184000.0, 'name': 'Start', 'interpolation': 2, 'value': 0.0, 'points': 0, 'min': 0.0, 'previous_point_x': -1, 'type': 'float', 'keyframe': False, 'choices': [], 'memo': '', 'readonly': False}), ('time', {'closest_point_x': 1.0, 'max': 5184000.0, 'name': 'Time', 'interpolation': 2, 'value': 0.0, 'points': 1, 'min': 0.0, 'previous_point_x': 1.0, 'type': 'float', 'keyframe': False, 'choices': [], 'memo': '', 'readonly': False}), ('layer', {'closest_point_x': -1, 'max': 20.0, 'name': 'Track', 'interpolation': 2, 'value': 4.0, 'points': 0, 'min': 0.0, 'previous_point_x': -1, 'type': 'int', 'keyframe': False, 'choices': [], 'memo': '', 'readonly': False}), ('volume', {'closest_point_x': 1.0, 'max': 1.0, 'name': 'Volume', 'interpolation': 2, 'value': 1.0, 'points': 1, 'min': 0.0, 'previous_point_x': 1.0, 'type': 'float', 'keyframe': False, 'choices': [], 'memo': '', 'readonly': False}), ('wave_color', {'closest_point_x': 1.0, 'blue': {'closest_point_x': 1.0, 'max': 255.0, 'name': 'Blue', 'interpolation': 0, 'value': 255.0, 'points': 1, 'min': 0.0, 'previous_point_x': 1.0, 'type': 'float', 'keyframe': False, 'choices': [], 'memo': '', 'readonly': False}, 'readonly': False, 'name': 'Wave Color', 'interpolation': 0, 'max': 255.0, 'value': 0.0, 'points': 1, 'min': 0.0, 'previous_point_x': 1.0, 'type': 'color', 'red': {'closest_point_x': 1.0, 'max': 255.0, 'name': 'Red', 'interpolation': 0, 'value': 0.0, 'points': 1, 'min': 0.0, 'previous_point_x': 1.0, 'type': 'float', 'keyframe': False, 'choices': [], 'memo': '', 'readonly': False}, 'choices': [], 'memo': '', 'keyframe': False, 'green': {'closest_point_x': 1.0, 'max': 255.0, 'name': 'Green', 'interpolation': 0, 'value': 123.0, 'points': 1, 'min': 0.0, 'previous_point_x': 1.0, 'type': 'float', 'keyframe': False, 'choices': [], 'memo': '', 'readonly': False}}), ('waveform', {'closest_point_x': -1, 'max': 1.0, 'name': 'Waveform', 'interpolation': 2, 'value': 0.0, 'points': 0, 'min': 0.0, 'previous_point_x': -1, 'type': 'int', 'keyframe': False, 'choices': [{'value': 1, 'selected': False, 'name': 'Yes'}, {'value': 0, 'selected': True, 'name': 'No'}], 'memo': '', 'readonly': False})])
preview_thread:INFO onModeChanged
Segmentation fault

**Comment by Sahrjd** [comment]
Same issue here. Openshot crashes when adding audio track of any type to the timeline.  Makes program unusable. 

OS: Windows 7 ver 6.1.7601
Program: OpenShot ver 2.3.3

**Comment by Interspock** [comment]
RESOLVED this crash in ver 2.3.4

**Comment by axmoran** [comment]
I'll have to check when I get off work, but if true whoever fixed is a hero.

**Comment by Sahrjd** [comment]
I installed 2.3.4 and now OpenSHot won't even run. Not that big of a deal since it was unusable for me at 2.3.3 since I couldn't add audio tracks. 

Screenshot of error on run attached.
![os error](https://cloud.githubusercontent.com/assets/29113614/26692450/9ce5c398-46b5-11e7-8e83-f3735c9f9982.PNG)

**Comment by luismgallegosc** [comment]
Crash issue when audio track was added is resolved in version 2.3.4. Does not crash and exported videos seem to be working fine.

An issue remains, though it does not pertain to this thread, but I'll mention it in case it is of use to someone. When applying a fade effect to a video clip and exporting the project in lo-res, said clip will come out completely black for its duration. Test was done exporting with a **Mobile 360p (320x240)** profile. I tried it with pictures too, and though it does not come out all black, the fading times do seem to be a little off.

There is no issue when exporting to hi-res. Tested it with a **HDV 720 24p (1280x720)** profile and it worked fine.

**Comment by Madking120** [comment]
I just updated to 2.3.4 and am still getting the launch.exe crash when I try to add my .flac audio file (47 mins) to the timeline. It works perfectly fine when I add a small test .flac (3 secs).

**Comment by vales** [comment]
The problem is still in v 2.3.4 playing mp3 audio files at time 2 '33' '. Both in preview and in export.
It resolves by converting mp3 audio files to ac3.

**Comment by DylanC** [comment]
Issue has since been resolved in the 2.3.4 release. If you still have an audio issue either report a more specific bug or add a comment to tickets about audio issues that are the same as yours. Thanks.

**Comment by gumbo-cms** [comment]
mine also crashes when adding/playing wav or mp3, haven't checked other sound formats though, my openshot version is 2.3.3 and I'm running Fedora 26 x86_64

Is there a fix already somewhere?

**Comment by Interspock** [comment]
Upgrade (2.3.4 fixes this) and done!

El sept. 6, 2017 8:30 AM, "gumbo-cms.net" <notifications@github.com>
escribió:

mine also crashes when adding/playing wav or mp3, haven't checked other
sound formats though, my openshot version is 2.3.3 and I'm running Fedora
26 x86_64

Is there a fix already somewhere?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/OpenShot/openshot-qt/issues/657#issuecomment-327455411>,
or mute the thread

**Comment by maxlefou** [comment]
Sorry but I have the 2.4.4 on Windows 10 and i'm still facing the problem.

Here's my log.
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/3144569/openshot-qt.log)
