### ISSUE TITLE
Reversed video doesn't play in reverse after export

### ISSUE THREAD

**Issue by alc59** [OpenShot/openshot-qt#667]
Openshot 2.3.3
cinnamon 18.1

reverse works inside of openshot but not after export
thanks

**Comment by Daveland3D** [comment]
Same issue. Reversed video does not render in reverse when exported to mp4 format.

Windows 8.1
OpenShot Version: 2.3.4

Imported video into new project
Placed it as a clip
Set Time > Normal > Backwards > 1X
Verified in the preview window that it works (plays backwards)
Exported the project
In the resulting video file (mp4, h.264, same profile as the original video), the clip is not reversed, but plays forward

**Comment by reddn** [comment]
Dup of #588 .  All timeline based functions do not work.

**Comment by DylanC** [comment]
Confirmed as fixed in #588

**Comment by SHOTbyGUN** [comment]
Still not fixed in 2.4.3.. 
- preview stutters but plays in reverse
- export shows still frame during reversed clip

**Comment by peanutbutterandcrackers** [comment]
I ran two tests just now: one using an image sequence and a `webm`. I reversed both using Right click > Time > Reverse > 1x and it worked just fine.

How did you reverse your videos? This certainly is strange.

**Comment by reddn** [comment]
I think it has been fixed. There were dups of the same issue.

**Comment by SHOTbyGUN** [comment]
I recorded a 2min video where I reproduce this issue in OpenShot 2.4.3
https://www.youtube.com/watch?v=rlXq-Dm1AaQ

**Comment by mikelacsa** [comment]
I tested this with ver 2.4.4 and it worked fine. I reproduced the steps done by @Daveland3D 

https://youtu.be/ljvhSGgItW0

**Comment by wjc86** [comment]
Just had the same issue, downloaded Openshot 2.5.1. Is anyone else still having this bug?

**Comment by ferdnyc** [comment]
@wjc86 
> Just had the same issue, downloaded Openshot 2.5.1. 

Since this issue is closed, please open a new one using the Bug Report template and fill in the details requested.

For this issue in particular, it would really help to have as much information about your project and media as possible. If you'd be able to upload your project (`.osp`) file, that would provide a lot of useful data about what OpenShot was _supposed_ to do, and we can try to figure out why it didn't.

Information about the format of the media file you were trying to reverse would also help. The MediaInfo app produces especially comprehensive data that would be helpful to include in your Issue.

As for the project file, you can either:
1. change the filename to end in `.txt`
1. create a zip file containing the `.osp`

Both text files and zip files can be attached directly to GitHub issue comments.
