### ISSUE TITLE
Has anyone had success using Openshot on Ubuntu 60 FPS

### ISSUE THREAD

**Issue by TombyT** [OpenShot/openshot-qt#789]
In short previewing these videos is virtually impossible and gets worse as editing continues. With patience one can edit a small amount of a clip at a time, save, and then close and re-open to essentially restart the process of diminishing performance.

Exporting also seems to be unstable. Rendering a 10 minute 1080p 60fps clip shows frequent greying out (freezing) and often won't finish. Usually the audio is garbled or distorted.

**Comment by TombyT** [comment]
Primarily I am having issues getting audio tracks to export without insane popping, cracking, etc. I will continue to attempt exporting the same project at different settings but the content is still a 60 fps mp4 with a single mp3.

**Comment by TombyT** [comment]
So I discovered that reducing the main clip volume to 0% while converting the underlying audio track from mp3 to .ac3 seems to have drastically improved though it's still far from the original audio quality which I'd have like to retain, as well would I have liked to retain the audio from the video clips.

**Comment by fabrixx** [comment]
i fixed by click on edit profile button & changing it in 60fps.

**Comment by DylanC** [comment]
@TombyT - You must use the correct profile for the type of video.

**Comment by fabrixx** [comment]
Working in 60 FPS Profile in old (also in my core i7) macchine may cause dramatics lags in interface caused by preview High resolution. Now i switch to 60 FPS at end editing to apply only transitions and volume level Hope bug fixed sono.

**Comment by TombyT** [comment]
Changing the profile to 60 fps does not seem to fix the problem

**Comment by fabrixx** [comment]
After changing profile from a  30 fps old work you have to remove & reapply all transitions & volume setting.
