### ISSUE TITLE
Too many CPU cores? Crash on 24 cores, no crash on 2 cores

### ISSUE THREAD

**Issue by rakoenig** [OpenShot/openshot-qt#841]
**System Details:** 
* Operating System / Distro: openSUSE Leap 42.2
* OpenShot Version: openshot-qt 2.3.1-3.54 
* _Please attach log files if crash_

[h264 @ 0x37e5ae0] Application has requested 24 threads. Using a thread count greater than 16 is not recommended.

**Issue Description and steps to reproduce:**

When exporting a video on my workstation with 24 CPU cores the process crashes after 1 or 2 percent. The same video exports fine on my notebook with the same software installed. Difference is that the notebook just has 2 cores. 

On the workstation I get the message from h264 that is listed above that says its not a good idea to reqest more then 16 threads.

So the question is, how can I limit the number of threads requested for exporting?

**Comment by DylanC** [comment]
@rakoenig - At the moment I do not think an option exists. However, the latest daily builds have much better safety using lots of threads. This issue may be resolved in the near future.

**Comment by DylanC** [comment]
@rakoenig - Can you try the v2.4 version now? It should work much better.

**Comment by DylanC** [comment]
@rakoenig - Please try v2.4. It works on 24+ thread systems

**Comment by rakoenig** [comment]
Tried v2.4 today, still crashes on export:
[h264 @ 0x1a236c0] Application has requested 24 threads. Using a thread count greater than 16 is not recommended.
Caught signal 11 (SIGSEGV)
---- Unhandled Exception: Stack Trace ----
  /tmp/.mount_S0Y7K9/usr/bin/_openshot.so (                                           + 0xdf633)  [0x7fd6f7ce5633]
  /tmp/.mount_S0Y7K9/usr/bin/_openshot.so (                                           + 0xdfdce)  [0x7fd6f7ce5dce]
  /tmp/.mount_S0Y7K9/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalFrameEx                        + 0x654b)  [0x7fd70eba4f7b]
  /tmp/.mount_S0Y7K9/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalCodeEx                         + 0x886 )  [0x7fd70eba8936]
  /tmp/.mount_S0Y7K9/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalFrameEx                        + 0x6742)  [0x7fd70eba5172]
  /tmp/.mount_S0Y7K9/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalCodeEx                         + 0x886 )  [0x7fd70eba8936]
  /tmp/.mount_S0Y7K9/usr/bin/libpython3.4m.so.1.0 (                                           + 0x209f66)  [0x7fd70eba8f66]
  /tmp/.mount_S0Y7K9/usr/bin/libpython3.4m.so.1.0 ( PyObject_Call                             + 0x68  )  [0x7fd70eb0a718]
  /tmp/.mount_S0Y7K9/usr/bin/libpython3.4m.so.1.0 (                                           + 0x15155d)  [0x7fd70eaf055d]
  /tmp/.mount_S0Y7K9/usr/bin/libpython3.4m.so.1.0 ( PyObject_Call                             + 0x68  )  [0x7fd70eb0a718]
  /tmp/.mount_S0Y7K9/usr/bin/libpython3.4m.so.1.0 ( PyEval_CallObjectWithKeywords             + 0x47  )  [0x7fd70eb80977]
  /tmp/.mount_S0Y7K9/usr/bin/PyQt5.QtCore.so ( PyQtSlot::invoke(_object*, _object*) const  + 0x50  )  [0x7fd702eb4840]
  /tmp/.mount_S0Y7K9/usr/bin/PyQt5.QtCore.so ( PyQtSlot::invoke(void**, _object*, void*) const  + 0xcf  )  [0x7fd702eb4caf]
  /tmp/.mount_S0Y7K9/usr/bin/PyQt5.QtCore.so ( PyQtSlotProxy::unislot(void**)            + 0x62  )  [0x7fd702ebf762]
  /tmp/.mount_S0Y7K9/usr/bin/PyQt5.QtCore.so ( PyQtSlotProxy::qt_metacall(QMetaObject::Call, int, void**)  + 0x57  )  [0x7fd702ec00d7]
  /tmp/.mount_S0Y7K9/usr/bin/libQt5Core.so.5 ( QMetaObject::activate(QObject*, int, int, void**)  + 0x8ad )  [0x7fd70ac1c36d]
  /tmp/.mount_S0Y7K9/usr/bin/libQt5Core.so.5 ( QMetaObject::activate(QObject*, int, int, void**)  + 0x7e6 )  [0x7fd70ac1c2a6]
  /tmp/.mount_S0Y7K9/usr/bin/libQt5Widgets.so.5 ( QAbstractButton::clicked(bool)            + 0x32  )  [0x7fd70bb27e42]
  /tmp/.mount_S0Y7K9/usr/bin/libQt5Widgets.so.5 (                                           + 0x231096)  [0x7fd70b8b1096]
  /tmp/.mount_S0Y7K9/usr/bin/libQt5Widgets.so.5 (                                           + 0x231bae)  [0x7fd70b8b1bae]
  /tmp/.mount_S0Y7K9/usr/bin/libQt5Widgets.so.5 ( QAbstractButton::mouseReleaseEvent(QMouseEvent*)  + 0xd4  )  [0x7fd70b8b1d24]
  /tmp/.mount_S0Y7K9/usr/bin/PyQt5.QtWidgets.so ( sipQPushButton::mouseReleaseEvent(QMouseEvent*)  + 0x7b  )  [0x7fd70c230fab]
  /tmp/.mount_S0Y7K9/usr/bin/libQt5Widgets.so.5 ( QWidget::event(QEvent*)                   + 0x405 )  [0x7fd70b7f5ea5]
  /tmp/.mount_S0Y7K9/usr/bin/PyQt5.QtWidgets.so ( sipQPushButton::event(QEvent*)            + 0x7b  )  [0x7fd70c2329ab]
  /tmp/.mount_S0Y7K9/usr/bin/libQt5Widgets.so.5 ( QApplicationPrivate::notify_helper(QObject*, QEvent*)  + 0x8c  )  [0x7fd70b7bac8c]
  /tmp/.mount_S0Y7K9/usr/bin/libQt5Widgets.so.5 ( QApplication::notify(QObject*, QEvent*)   + 0x10e1)  [0x7fd70b7c0b61]
  /tmp/.mount_S0Y7K9/usr/bin/PyQt5.QtWidgets.so ( sipQApplication::notify(QObject*, QEvent*)  + 0x86  )  [0x7fd70c190426]
  /tmp/.mount_S0Y7K9/usr/bin/libQt5Core.so.5 ( QCoreApplication::notifyInternal(QObject*, QEvent*)  + 0x6d  )  [0x7fd70abf4c2d]
  /tmp/.mount_S0Y7K9/usr/bin/libQt5Widgets.so.5 ( QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool)  + 0x391 )  [0x7fd70b7be9e1]
  /tmp/.mount_S0Y7K9/usr/bin/libQt5Widgets.so.5 (                                           + 0x192bbf)  [0x7fd70b812bbf]
  /tmp/.mount_S0Y7K9/usr/bin/libQt5Widgets.so.5 (                                           + 0x1949bb)  [0x7fd70b8149bb]
  /tmp/.mount_S0Y7K9/usr/bin/libQt5Widgets.so.5 ( QApplicationPrivate::notify_helper(QObject*, QEvent*)  + 0x8c  )  [0x7fd70b7bac8c]
  /tmp/.mount_S0Y7K9/usr/bin/libQt5Widgets.so.5 ( QApplication::notify(QObject*, QEvent*)   + 0x3d6 )  [0x7fd70b7bfe56]
  /tmp/.mount_S0Y7K9/usr/bin/PyQt5.QtWidgets.so ( sipQApplication::notify(QObject*, QEvent*)  + 0x86  )  [0x7fd70c190426]
  /tmp/.mount_S0Y7K9/usr/bin/libQt5Core.so.5 ( QCoreApplication::notifyInternal(QObject*, QEvent*)  + 0x6d  )  [0x7fd70abf4c2d]
  /tmp/.mount_S0Y7K9/usr/bin/libQt5Gui.so.5 ( QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*)  + 0x39c )  [0x7fd70b11425c]
  /tmp/.mount_S0Y7K9/usr/bin/libQt5Gui.so.5 ( QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*)  + 0x115 )  [0x7fd70b115925]
  /tmp/.mount_S0Y7K9/usr/bin/libQt5Gui.so.5 ( QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>)  + 0x28  )  [0x7fd70b0fe858]
  /tmp/.mount_S0Y7K9/usr/bin/platforms/libqxcb.so (                                           + 0x4f5b0)  [0x7fd6f02b75b0]
  /usr/lib64/libglib-2.0.so.0    ( g_main_context_dispatch                   + 0x254 )  [0x7fd709ed8134]
  /usr/lib64/libglib-2.0.so.0    (                                           + 0x4c388)  [0x7fd709ed8388]
  /usr/lib64/libglib-2.0.so.0    ( g_main_context_iteration                  + 0x2c  )  [0x7fd709ed842c]
  /tmp/.mount_S0Y7K9/usr/bin/libQt5Core.so.5 ( QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>)  + 0x5c  )  [0x7fd70ac4198c]
  /tmp/.mount_S0Y7K9/usr/bin/libQt5Core.so.5 ( QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>)  + 0x11b )  [0x7fd70abf396b]
  /tmp/.mount_S0Y7K9/usr/bin/libQt5Widgets.so.5 ( QDialog::exec()                           + 0x20d )  [0x7fd70b9a1e0d]
  /tmp/.mount_S0Y7K9/usr/bin/PyQt5.QtWidgets.so (                                           + 0x374c35)  [0x7fd70c21dc35]
  /tmp/.mount_S0Y7K9/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalFrameEx                        + 0x6d79)  [0x7fd70eba57a9]
  /tmp/.mount_S0Y7K9/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalCodeEx                         + 0x886 )  [0x7fd70eba8936]
  /tmp/.mount_S0Y7K9/usr/bin/libpython3.4m.so.1.0 (                                           + 0x209f66)  [0x7fd70eba8f66]
  /tmp/.mount_S0Y7K9/usr/bin/libpython3.4m.so.1.0 ( PyObject_Call                             + 0x68  )  [0x7fd70eb0a718]
  /tmp/.mount_S0Y7K9/usr/bin/libpython3.4m.so.1.0 (                                           + 0x15155d)  [0x7fd70eaf055d]
  /tmp/.mount_S0Y7K9/usr/bin/libpython3.4m.so.1.0 ( PyObject_Call                             + 0x68  )  [0x7fd70eb0a718]
  /tmp/.mount_S0Y7K9/usr/bin/libpython3.4m.so.1.0 ( PyEval_CallObjectWithKeywords             + 0x47  )  [0x7fd70eb80977]
  /tmp/.mount_S0Y7K9/usr/bin/PyQt5.QtCore.so ( PyQtSlot::invoke(_object*, _object*) const  + 0x50  )  [0x7fd702eb4840]
  /tmp/.mount_S0Y7K9/usr/bin/PyQt5.QtCore.so ( PyQtSlot::invoke(void**, _object*, void*) const  + 0xcf  )  [0x7fd702eb4caf]
  /tmp/.mount_S0Y7K9/usr/bin/PyQt5.QtCore.so ( PyQtSlotProxy::unislot(void**)            + 0x62  )  [0x7fd702ebf762]
  /tmp/.mount_S0Y7K9/usr/bin/PyQt5.QtCore.so ( PyQtSlotProxy::qt_metacall(QMetaObject::Call, int, void**)  + 0x57  )  [0x7fd702ec00d7]
  /tmp/.mount_S0Y7K9/usr/bin/libQt5Core.so.5 ( QMetaObject::activate(QObject*, int, int, void**)  + 0x8ad )  [0x7fd70ac1c36d]
  /tmp/.mount_S0Y7K9/usr/bin/libQt5Widgets.so.5 ( QAction::triggered(bool)                  + 0x32  )  [0x7fd70b7b3a52]
  /tmp/.mount_S0Y7K9/usr/bin/libQt5Widgets.so.5 ( QAction::activate(QAction::ActionEvent)   + 0xe8  )  [0x7fd70b7b5f38]
---- End of Stack Trace ----
QLibraryPrivate::unload succeeded on "/tmp/.mount_S0Y7K9/usr/bin/imageformats/libqgif.so"  
QLibraryPrivate::unload succeeded on "/tmp/.mount_S0Y7K9/usr/bin/imageformats/libqico.so"  
QLibraryPrivate::unload succeeded on "/tmp/.mount_S0Y7K9/usr/bin/imageformats/libqjpeg.so"  
QLibraryPrivate::unload succeeded on "/tmp/.mount_S0Y7K9/usr/bin/imageformats/libqsvg.so"  
QLibraryPrivate::unload succeeded on "/tmp/.mount_S0Y7K9/usr/bin/platforms/libqxcb.so"  
QLibraryPrivate::unload succeeded on "Xcursor" (faked)

**Comment by DylanC** [comment]
Hi @rakoenig - I have been notified this has been fixed in the latest daily build.

**Comment by rakoenig** [comment]
Well something changed. I downloaded the daily build appimage from October 1st. Now when rendering the App doesn't crash and disappears, it crashes and the windows remain frozen. And on the terminal window I still see that the H264 codec complains that it is used with more than 16 threads.

**Comment by DylanC** [comment]
@rakoenig - Thanks for the feedback. Sounds like we are further with this but it is not yet 100% sorted.

**Comment by DylanC** [comment]
@rakoenig - Just checking in with you. Does this still happen in v2.4.1?

**Comment by DylanC** [comment]
@rakoenig - Any luck just yet?

**Comment by rakoenig** [comment]
Am 24.11.2017 um 12:17 schrieb DylanC:
> @rakoenig <https://github.com/rakoenig> - Any luck just yet?


Behaving different now. Rendering freezes at 5% and the terminal window
where I started the appimage now shose this as "famous last words":

      export:INFO (7, 'Surround (3 Kanäle)')
      export:INFO (1551, 'Surround (5+1 Kanäle)')
      export:INFO (1599, 'Surround (7+1 Kanäle)')
      export:INFO /tmp/.mount_09WL9V/usr/bin/profiles/square_pal_wide
      export:INFO AVI (h.264)
      export:INFO updateChannels
      export:INFO /tmp/.mount_09WL9V/usr/bin/profiles/square_pal_wide
      export:INFO /tmp/.mount_09WL9V/usr/bin/profiles/atsc_1080p_25
      export:INFO /tmp/.mount_09WL9V/usr/bin/profiles/atsc_1080p_25
      export:INFO Low
      export:INFO None
      export:INFO MP4 (h.264)
      export:INFO None
      export:INFO /tmp/.mount_09WL9V/usr/bin/profiles/square_pal_wide
      export:INFO /tmp/.mount_09WL9V/usr/bin/profiles/square_pal_wide
      export:INFO /tmp/.mount_09WL9V/usr/bin/profiles/atsc_1080p_25
      export:INFO /tmp/.mount_09WL9V/usr/bin/profiles/atsc_1080p_25
      export:INFO Low
      export:INFO High
      export:INFO Valid framerate detected, sending to libopenshot: 25.0
      export:INFO None
      export:INFO Flickr-HD
      export:INFO None
      export:INFO None
      export:INFO /tmp/.mount_09WL9V/usr/bin/profiles/atsc_1080p_25
      export:INFO Low
      export:INFO High
      export:INFO YouTube-HD
      export:INFO None
      export:INFO None
      export:INFO /tmp/.mount_09WL9V/usr/bin/profiles/atsc_1080p_25
      export:INFO Low
      export:INFO High
      export:INFO /srv/Video/Guitartest.mp4
[libx264 @ 0x29b1c20] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2
[libx264 @ 0x29b1c20] profile High, level 4.0
[libx264 @ 0x29b1c20] 264 - core 142 r2389 956c8d8 - H.264/MPEG-4 AVC
codec - Copyleft 2003-2014 - http://www.videolan.org/x264.html -
options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7
psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1
8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2
threads=16 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1
interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=2
keyint=12 keyint_min=1 scenecut=40 intra_refresh=0 rc_lookahead=12
rc=abr mbtree=1 bitrate=8000 ratetol=1.0 qcomp=0.60 qpmin=2 qpmax=30
qpstep=4 ip_ratio=1.25 aq=1:1.00
Caught signal 11 (SIGSEGV)
---- Unhandled Exception: Stack Trace ----
  /tmp/.mount_09WL9V/usr/bin/_openshot.so (
             + 0xdb819)  [0x7f4b8e6c8819]
  /tmp/.mount_09WL9V/usr/bin/_openshot.so (
             + 0xdbd02)  [0x7f4b8e6c8d02]
  /tmp/.mount_09WL9V/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalFrameEx
                     + 0x654b)  [0x7f4ba51aff7b]
  /tmp/.mount_09WL9V/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalCodeEx
                     + 0x886 )  [0x7f4ba51b3936]
  /tmp/.mount_09WL9V/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalFrameEx
                     + 0x6742)  [0x7f4ba51b0172]
  /tmp/.mount_09WL9V/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalCodeEx
                     + 0x886 )  [0x7f4ba51b3936]
  /tmp/.mount_09WL9V/usr/bin/libpython3.4m.so.1.0 (
                     + 0x209f66)  [0x7f4ba51b3f66]
  /tmp/.mount_09WL9V/usr/bin/libpython3.4m.so.1.0 ( PyObject_Call
                     + 0x68  )  [0x7f4ba5115718]
  /tmp/.mount_09WL9V/usr/bin/libpython3.4m.so.1.0 (
                     + 0x15155d)  [0x7f4ba50fb55d]
  /tmp/.mount_09WL9V/usr/bin/libpython3.4m.so.1.0 ( PyObject_Call
                     + 0x68  )  [0x7f4ba5115718]
  /tmp/.mount_09WL9V/usr/bin/libpython3.4m.so.1.0 (
PyEval_CallObjectWithKeywords             + 0x47  )  [0x7f4ba518b977]
  /tmp/.mount_09WL9V/usr/bin/PyQt5.QtCore.so (
PyQtSlot::invoke(_object*, _object*) const  + 0x50  )  [0x7f4b994a2840]
  /tmp/.mount_09WL9V/usr/bin/PyQt5.QtCore.so ( PyQtSlot::invoke(void**,
_object*, void*) const  + 0xcf  )  [0x7f4b994a2caf]
  /tmp/.mount_09WL9V/usr/bin/PyQt5.QtCore.so (
PyQtSlotProxy::unislot(void**)            + 0x62  )  [0x7f4b994ad762]
  /tmp/.mount_09WL9V/usr/bin/PyQt5.QtCore.so (
PyQtSlotProxy::qt_metacall(QMetaObject::Call, int, void**)  + 0x57  )
[0x7f4b994ae0d7]
  /tmp/.mount_09WL9V/usr/bin/libQt5Core.so.5 (
QMetaObject::activate(QObject*, int, int, void**)  + 0x8ad )
[0x7f4ba122736d]
  /tmp/.mount_09WL9V/usr/bin/libQt5Core.so.5 (
QMetaObject::activate(QObject*, int, int, void**)  + 0x7e6 )
[0x7f4ba12272a6]
  /tmp/.mount_09WL9V/usr/bin/libQt5Widgets.so.5 (
QAbstractButton::clicked(bool)            + 0x32  )  [0x7f4ba2132e42]
  /tmp/.mount_09WL9V/usr/bin/libQt5Widgets.so.5 (
                   + 0x231096)  [0x7f4ba1ebc096]
  /tmp/.mount_09WL9V/usr/bin/libQt5Widgets.so.5 (
                   + 0x231bae)  [0x7f4ba1ebcbae]
  /tmp/.mount_09WL9V/usr/bin/libQt5Widgets.so.5 (
QAbstractButton::mouseReleaseEvent(QMouseEvent*)  + 0xd4  )
[0x7f4ba1ebcd24]
  /tmp/.mount_09WL9V/usr/bin/PyQt5.QtWidgets.so (
sipQPushButton::mouseReleaseEvent(QMouseEvent*)  + 0x7b  )  [0x7f4ba283bfab]
  /tmp/.mount_09WL9V/usr/bin/libQt5Widgets.so.5 (
QWidget::event(QEvent*)                   + 0x405 )  [0x7f4ba1e00ea5]
  /tmp/.mount_09WL9V/usr/bin/PyQt5.QtWidgets.so (
sipQPushButton::event(QEvent*)            + 0x7b  )  [0x7f4ba283d9ab]
  /tmp/.mount_09WL9V/usr/bin/libQt5Widgets.so.5 (
QApplicationPrivate::notify_helper(QObject*, QEvent*)  + 0x8c  )
[0x7f4ba1dc5c8c]
  /tmp/.mount_09WL9V/usr/bin/libQt5Widgets.so.5 (
QApplication::notify(QObject*, QEvent*)   + 0x10e1)  [0x7f4ba1dcbb61]
  /tmp/.mount_09WL9V/usr/bin/PyQt5.QtWidgets.so (
sipQApplication::notify(QObject*, QEvent*)  + 0x86  )  [0x7f4ba279b426]
  /tmp/.mount_09WL9V/usr/bin/libQt5Core.so.5 (
QCoreApplication::notifyInternal(QObject*, QEvent*)  + 0x6d  )
[0x7f4ba11ffc2d]
  /tmp/.mount_09WL9V/usr/bin/libQt5Widgets.so.5 (
QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*,
QWidget*, QWidget**, QPointer<QWidget>&, bool)  + 0x391 )  [0x7f4ba1dc99e1]
  /tmp/.mount_09WL9V/usr/bin/libQt5Widgets.so.5 (
                   + 0x192bbf)  [0x7f4ba1e1dbbf]
  /tmp/.mount_09WL9V/usr/bin/libQt5Widgets.so.5 (
                   + 0x1949bb)  [0x7f4ba1e1f9bb]
  /tmp/.mount_09WL9V/usr/bin/libQt5Widgets.so.5 (
QApplicationPrivate::notify_helper(QObject*, QEvent*)  + 0x8c  )
[0x7f4ba1dc5c8c]
  /tmp/.mount_09WL9V/usr/bin/libQt5Widgets.so.5 (
QApplication::notify(QObject*, QEvent*)   + 0x3d6 )  [0x7f4ba1dcae56]
  /tmp/.mount_09WL9V/usr/bin/PyQt5.QtWidgets.so (
sipQApplication::notify(QObject*, QEvent*)  + 0x86  )  [0x7f4ba279b426]
  /tmp/.mount_09WL9V/usr/bin/libQt5Core.so.5 (
QCoreApplication::notifyInternal(QObject*, QEvent*)  + 0x6d  )
[0x7f4ba11ffc2d]
  /tmp/.mount_09WL9V/usr/bin/libQt5Gui.so.5 (
QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*)
 + 0x39c )  [0x7f4ba171f25c]
  /tmp/.mount_09WL9V/usr/bin/libQt5Gui.so.5 (
QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*)
 + 0x115 )  [0x7f4ba1720925]
  /tmp/.mount_09WL9V/usr/bin/libQt5Gui.so.5 (
QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>)
 + 0x28  )  [0x7f4ba1709858]
  /tmp/.mount_09WL9V/usr/bin/platforms/libqxcb.so (
                     + 0x4f5b0)  [0x7f4b86c7c5b0]
  /usr/lib64/libglib-2.0.so.0    ( g_main_context_dispatch
    + 0x254 )  [0x7f4ba04e3134]
  /usr/lib64/libglib-2.0.so.0    (
    + 0x4c388)  [0x7f4ba04e3388]
  /usr/lib64/libglib-2.0.so.0    ( g_main_context_iteration
    + 0x2c  )  [0x7f4ba04e342c]
  /tmp/.mount_09WL9V/usr/bin/libQt5Core.so.5 (
QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>)
 + 0x5c  )  [0x7f4ba124c98c]
  /tmp/.mount_09WL9V/usr/bin/libQt5Core.so.5 (
QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>)  + 0x11b )
[0x7f4ba11fe96b]
  /tmp/.mount_09WL9V/usr/bin/libQt5Widgets.so.5 ( QDialog::exec()
                   + 0x20d )  [0x7f4ba1face0d]
  /tmp/.mount_09WL9V/usr/bin/PyQt5.QtWidgets.so (
                   + 0x374c35)  [0x7f4ba2828c35]
  /tmp/.mount_09WL9V/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalFrameEx
                     + 0x6d79)  [0x7f4ba51b07a9]
  /tmp/.mount_09WL9V/usr/bin/libpython3.4m.so.1.0 ( PyEval_EvalCodeEx
                     + 0x886 )  [0x7f4ba51b3936]
  /tmp/.mount_09WL9V/usr/bin/libpython3.4m.so.1.0 (
                     + 0x209f66)  [0x7f4ba51b3f66]
  /tmp/.mount_09WL9V/usr/bin/libpython3.4m.so.1.0 ( PyObject_Call
                     + 0x68  )  [0x7f4ba5115718]
  /tmp/.mount_09WL9V/usr/bin/libpython3.4m.so.1.0 (
                     + 0x15155d)  [0x7f4ba50fb55d]
  /tmp/.mount_09WL9V/usr/bin/libpython3.4m.so.1.0 ( PyObject_Call
                     + 0x68  )  [0x7f4ba5115718]
  /tmp/.mount_09WL9V/usr/bin/libpython3.4m.so.1.0 (
PyEval_CallObjectWithKeywords             + 0x47  )  [0x7f4ba518b977]
  /tmp/.mount_09WL9V/usr/bin/PyQt5.QtCore.so (
PyQtSlot::invoke(_object*, _object*) const  + 0x50  )  [0x7f4b994a2840]
  /tmp/.mount_09WL9V/usr/bin/PyQt5.QtCore.so ( PyQtSlot::invoke(void**,
_object*, void*) const  + 0xcf  )  [0x7f4b994a2caf]
  /tmp/.mount_09WL9V/usr/bin/PyQt5.QtCore.so (
PyQtSlotProxy::unislot(void**)            + 0x62  )  [0x7f4b994ad762]
  /tmp/.mount_09WL9V/usr/bin/PyQt5.QtCore.so (
PyQtSlotProxy::qt_metacall(QMetaObject::Call, int, void**)  + 0x57  )
[0x7f4b994ae0d7]
  /tmp/.mount_09WL9V/usr/bin/libQt5Core.so.5 (
QMetaObject::activate(QObject*, int, int, void**)  + 0x8ad )
[0x7f4ba122736d]
  /tmp/.mount_09WL9V/usr/bin/libQt5Widgets.so.5 (
QAction::triggered(bool)                  + 0x32  )  [0x7f4ba1dbea52]
  /tmp/.mount_09WL9V/usr/bin/libQt5Widgets.so.5 (
QAction::activate(QAction::ActionEvent)   + 0xe8  )  [0x7f4ba1dc0f38]
---- End of Stack Trace ----
QLibraryPrivate::unload succeeded on
"/tmp/.mount_09WL9V/usr/bin/imageformats/libqgif.so"
QLibraryPrivate::unload succeeded on
"/tmp/.mount_09WL9V/usr/bin/imageformats/libqico.so"
QLibraryPrivate::unload succeeded on
"/tmp/.mount_09WL9V/usr/bin/imageformats/libqjpeg.so"
QLibraryPrivate::unload succeeded on
"/tmp/.mount_09WL9V/usr/bin/imageformats/libqsvg.so"
QLibraryPrivate::unload succeeded on
"/tmp/.mount_09WL9V/usr/bin/platforms/libqxcb.so"
QLibraryPrivate::unload succeeded on "Xcursor" (faked)
Caught signal 11 (SIGSEGV)
---- Unhandled Exception: Stack Trace ----

Thanks,
Rainer
-- 
Rainer Koenig, Diplom-Informatiker (FH), Augsburg, Germany
http://koenig-haunstetten.de

**Comment by DylanC** [comment]
@rakoenig  - Thanks! This will be solved some day... some day in the future.   :)

**Comment by DylanC** [comment]
@rakoenig - Try v2.4.3 and let us know if you still have a problem.

**Comment by rakoenig** [comment]
Downloaded the v2.4.3 app image. Works perfeclty fine now, no crashes during rendering. Thanks a lot for the support.

**Comment by DylanC** [comment]
@rakoenig - Glad to hear it. Many fixes went in for multiple core support in this release.
